/**
 * GLSL Code Generation from Scene Graph IR
 */

import { log } from './app-context.js';

export function generateGlslFromSceneGraph(sceneGraph) {
  const sg = Array.isArray(sceneGraph) ? sceneGraph : [];
  const lines = [];

  const byId = new Map();
  sg.forEach(node => {
    if (node && node.id) byId.set(node.id, node);
  });

  // Detect template usage for function generation optimization
  const templateUsage = new Map(); // template name -> [node ids]
  sg.forEach(node => {
    if (node && node._template) {
      const templateName = node._template.template;
      if (!templateUsage.has(templateName)) {
        templateUsage.set(templateName, []);
      }
      templateUsage.get(templateName).push(node.id);
    }
  });

  // Templates used 2+ times should become GLSL functions
  const templatesToOptimize = new Set();
  templateUsage.forEach((nodeIds, templateName) => {
    if (nodeIds.length >= 2) {
      templatesToOptimize.add(templateName);
      log(`Template '${templateName}' used ${nodeIds.length} times - generating GLSL function`, "info");
    }
  });

  const visited = new Set();
  const temp = new Set();
  const sorted = [];
  let hasCycle = false;

  function visit(node) {
    if (!node || !node.id) return;
    if (temp.has(node.id)) {
      hasCycle = true;
      log("Cycle detected involving node '" + node.id + "'", "error");
      return;
    }
    if (visited.has(node.id)) return;
    temp.add(node.id);
    const ins = node.inputs || {};
    Object.values(ins).forEach(depId => {
      const dep = byId.get(depId);
      if (dep) visit(dep);
    });
    temp.delete(node.id);
    visited.add(node.id);
    sorted.push(node);
  }

  sg.forEach(n => visit(n));
  const ordered = sorted.length ? sorted : sg;

  const funcNameById = new Map();
  ordered.forEach((node, idx) => {
    const safe = (node.id || ("node" + idx)).replace(/[^a-zA-Z0-9_]/g, "_");
    let fn = "g_sdfn_" + safe;
    if (funcNameById.has(node.id)) fn += "_" + idx;
    funcNameById.set(node.id, fn);
  });

  function exprToGLSL(v, fallback) {
    if (v == null) return fallback;
    if (Array.isArray(v)) return exprToGLSL(v[0], fallback);
    if (typeof v === "number") return String(v);
    if (typeof v === "string") {
      return v.replace(/\btime\b/g, "u_time");
    }
    return fallback;
  }

  function vec3Expr(arr, def, label) {
    if (!Array.isArray(arr) || arr.length === 0) {
      const c = exprToGLSL(arr, def);
      return "vec3(" + c + ", " + c + ", " + c + ")";
    }
    let a = arr.slice();
    if (a.length === 1) {
      a = [a[0], a[0], a[0]];
    } else if (a.length === 2) {
      log("DSL: " + label + " array has 2 components; repeating last", "info");
      a = [a[0], a[1], a[1]];
    } else if (a.length > 3) {
      log("DSL: " + label + " array has >3 components; extra ignored", "info");
      a = a.slice(0, 3);
    }
    const x = exprToGLSL(a[0], def);
    const y = exprToGLSL(a[1], def);
    const z = exprToGLSL(a[2], def);
    return "vec3(" + x + ", " + y + ", " + z + ")";
  }

  function getInputCalls(node) {
    const inputs = node.inputs || {};
    let ids = node.inputOrder && node.inputOrder.length
      ? node.inputOrder.slice()
      : Object.values(inputs);
    ids = ids.filter(Boolean);
    const calls = [];
    ids.forEach(inpId => {
      const fn = funcNameById.get(inpId);
      if (fn) calls.push(fn + "(p)");
      else calls.push("vec4(9999.0, 1.0, 1.0, 1.0)");
    });
    return calls;
  }

  lines.push("// Autogenerated GLSL from SDF scene graph");
  lines.push("// Nodes: " + sg.length + " (ordered: " + ordered.length + ")");
  if (hasCycle) lines.push("// WARNING: graph contains cycles");
  lines.push("");
  lines.push("float g_sdSphere(vec3 p, float r) { return length(p) - r; }");
  lines.push("float g_sdBox(vec3 p, vec3 b) {");
  lines.push("  vec3 d = abs(p) - b;");
  lines.push("  return min(max(d.x, max(d.y, d.z)), 0.0) + length(max(d, 0.0));");
  lines.push("}");
  lines.push("float g_opSmoothUnion(float d1, float d2, float k) {");
  lines.push("  float h = clamp(0.5 + 0.5 * (d2 - d1) / k, 0.0, 1.0);");
  lines.push("  return mix(d2, d1, h) - k * h * (1.0 - h);");
  lines.push("}");
  lines.push("float g_opSubtract(float d1, float d2) {");
  lines.push("  return max(d1, -d2);");
  lines.push("}");
  lines.push("vec3 g_rotateXYZ(vec3 p, vec3 r) {");
  lines.push("  float cx = cos(r.x), sx = sin(r.x);");
  lines.push("  float cy = cos(r.y), sy = sin(r.y);");
  lines.push("  float cz = cos(r.z), sz = sin(r.z);");
  lines.push("  mat3 rx = mat3(1.0,0.0,0.0, 0.0,cx,-sx, 0.0,sx,cx);");
  lines.push("  mat3 ry = mat3(cy,0.0,sy, 0.0,1.0,0.0, -sy,0.0,cy);");
  lines.push("  mat3 rz = mat3(cz,-sz,0.0, sz,cz,0.0, 0.0,0.0,1.0);");
  lines.push("  return rz * ry * rx * p;");
  lines.push("}");
  lines.push("float g_sdCapsule(vec3 p, vec3 a, vec3 b, float r) {");
  lines.push("  vec3 pa = p - a;");
  lines.push("  vec3 ba = b - a;");
  lines.push("  float h = clamp(dot(pa, ba)/dot(ba, ba), 0.0, 1.0);");
  lines.push("  return length(pa - ba * h) - r;");
  lines.push("}");
  lines.push("float g_sdEllipsoid(vec3 p, vec3 r) {");
  lines.push("  float k0 = length(p / r);");
  lines.push("  float k1 = length(p / (r * r));");
  lines.push("  return k0 * (k0 - 1.0) / k1;");
  lines.push("}");
  lines.push("float g_sdPlane(vec3 p, vec3 n, float d) {");
  lines.push("  return dot(p, normalize(n)) + d;");
  lines.push("}");
  lines.push("float g_sdTorus(vec3 p, float majorR, float minorR) {");
  lines.push("  vec2 q = vec2(length(p.xz) - majorR, p.y);");
  lines.push("  return length(q) - minorR;");
  lines.push("}");
  lines.push("float g_sdCylinder(vec3 p, float r, float h) {");
  lines.push("  vec2 d = abs(vec2(length(p.xz), p.y)) - vec2(r, h);");
  lines.push("  return min(max(d.x, d.y), 0.0) + length(max(d, 0.0));");
  lines.push("}");
  lines.push("float g_sdCone(vec3 p, float r, float h) {");
  lines.push("  vec2 q = vec2(length(p.xz), p.y);");
  lines.push("  vec2 tip = q - vec2(0.0, h);");
  lines.push("  vec2 mantle = vec2(sin(atan(r, h)), -cos(atan(r, h)));");
  lines.push("  float d = max(dot(tip, tip), dot(q, mantle));");
  lines.push("  return sqrt(max(d, 0.0));");
  lines.push("}");
  lines.push("float g_opSmoothSubtract(float d1, float d2, float k) {");
  lines.push("  float h = clamp(0.5 - 0.5 * (d2 + d1) / k, 0.0, 1.0);");
  lines.push("  return mix(d2, -d1, h) + k * h * (1.0 - h);");
  lines.push("}");
  lines.push("");
  // quaternion helpers
  lines.push("vec4 g_quat(float w, float x, float y, float z) {");
  lines.push("  return normalize(vec4(x, y, z, w));");
  lines.push("}");
  lines.push("vec4 g_quatMul(vec4 a, vec4 b) {");
  lines.push("  return vec4(");
  lines.push("    a.w*b.x + a.x*b.w + a.y*b.z - a.z*b.y,");
  lines.push("    a.w*b.y - a.x*b.z + a.y*b.w + a.z*b.x,");
  lines.push("    a.w*b.z + a.x*b.y - a.y*b.x + a.z*b.w,");
  lines.push("    a.w*b.w - dot(a.xyz, b.xyz)");
  lines.push("  );");
  lines.push("}");
  lines.push("vec4 g_quatEuler(float rx, float ry, float rz) {");
  lines.push("  float hx = rx * 0.5;");
  lines.push("  float hy = ry * 0.5;");
  lines.push("  float hz = rz * 0.5;");
  lines.push("  vec4 qx = vec4(sin(hx), 0.0, 0.0, cos(hx));");
  lines.push("  vec4 qy = vec4(0.0, sin(hy), 0.0, cos(hy));");
  lines.push("  vec4 qz = vec4(0.0, 0.0, sin(hz), cos(hz));");
  lines.push("  vec4 q = g_quatMul(g_quatMul(qz, qy), qx);");
  lines.push("  return normalize(q);");
  lines.push("}");
  lines.push("vec4 g_quatAxisAngle(vec3 axis, float angle) {");
  lines.push("  float h = angle * 0.5;");
  lines.push("  float s = sin(h);");
  lines.push("  return normalize(vec4(axis * s, cos(h)));");
  lines.push("}");
  lines.push("vec3 g_qrotate(vec3 p, vec4 q) {");
  lines.push("  vec3 t = 2.0 * cross(q.xyz, p);");
  lines.push("  return p + q.w * t + cross(q.xyz, t);");
  lines.push("}");
  lines.push("// DSL quaternion helpers");
  lines.push("vec4 quat(float w, float x, float y, float z) { return g_quat(w,x,y,z); }");
  lines.push("vec4 quatEuler(float rx, float ry, float rz) { return g_quatEuler(rx,ry,rz); }");
  lines.push("vec4 quatAxisAngle(vec3 axis, float angle) { return g_quatAxisAngle(axis,angle); }");
  lines.push("");

  if (!sg.length) {
    lines.push("// No nodes; sampleGraphScene returns empty density.");
    lines.push("vec4 sampleGraphScene(vec3 p, out float sdf, out vec3 surfCol) {");
    lines.push("  sdf = 9999.0;");
    lines.push("  surfCol = vec3(1.0);");
    lines.push("  float den = smoothstep(0.1, -0.1, sdf);");
    lines.push("  return vec4(vec3(den), den);");
    lines.push("}");
    return lines.join("\n");
  }

  // Generate GLSL functions for optimized templates
  sg.filter(node => node && node._isTemplate).forEach(templateNode => {
    const templateName = templateNode.templateName;

    if (!templatesToOptimize.has(templateName)) {
      return; // Skip templates used only once
    }

    lines.push(`// Template function: ${templateName}(${templateNode.params.join(', ')})`);
    lines.push(`// Used ${templateUsage.get(templateName).length} times - optimized as GLSL function`);

    // Generate function signature with proper parameter types
    const paramDecls = templateNode.params.map(p => {
      // Infer type from parameter usage in body
      const bodyStr = templateNode.body.join(' ');
      if (bodyStr.includes(`[${p}`)) return `vec3 ${p}`; // Used in array context
      return `float ${p}`; // Default to float
    });

    lines.push(`vec4 template_${templateName}(vec3 p ${paramDecls.length > 0 ? ', ' + paramDecls.join(', ') : ''}) {`);

    // Compile template body statements to GLSL
    const bodyLines = compileTemplateBodyToGLSL(templateNode.body, templateNode.params);
    bodyLines.forEach(line => lines.push(`  ${line}`));

    lines.push(`}`);
    lines.push(``);
  });

  // Helper function to compile template body DSL to GLSL
  function compileTemplateBodyToGLSL(bodyStatements, templateParams) {
    const glslLines = [];
    const localVars = new Map(); // Track local variable types

    bodyStatements.forEach(stmt => {
      const returnMatch = stmt.match(/^return\s+(.+)$/);
      if (returnMatch) {
        // Return statement - compile expression and return
        const expr = returnMatch[1];
        const glslExpr = compileExpressionToGLSL(expr, templateParams, localVars);
        glslLines.push(`return ${glslExpr};`);
        return;
      }

      // Regular assignment: varName = expression
      const assignMatch = stmt.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/);
      if (assignMatch) {
        const varName = assignMatch[1];
        const expr = assignMatch[2];
        const glslExpr = compileExpressionToGLSL(expr, templateParams, localVars);

        // Infer variable type from expression
        const varType = inferExpressionType(expr, glslExpr);
        glslLines.push(`${varType} ${varName} = ${glslExpr};`);
        localVars.set(varName, varType);
      }
    });

    return glslLines;
  }

  // Helper to infer GLSL type from expression
  function inferExpressionType(dslExpr, glslExpr) {
    // Check if expression is a function call that returns vec4
    if (dslExpr.match(/^(sphere|box|capsule|ellipsoid|plane|torus|cylinder|cone|subtract|union|smoothUnion|smoothSubtract)\s*\(/)) {
      return 'vec4';
    }
    // Check if result looks like vec3 or vec4
    if (glslExpr.startsWith('vec3(') || glslExpr.startsWith('vec4(')) {
      return glslExpr.startsWith('vec3(') ? 'vec3' : 'vec4';
    }
    // Default to float for arithmetic expressions
    return 'float';
  }

  // Helper to compile a single expression to GLSL
  function compileExpressionToGLSL(expr, templateParams, localVars) {
    // Parse function call: funcName(arg1=val1, arg2=val2)
    const callMatch = expr.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)$/);
    if (!callMatch) {
      // Not a function call - could be variable, arithmetic, etc.
      // Convert time to u_time and pass through
      return exprToGLSL(expr, expr);
    }

    const funcName = callMatch[1];
    const argsStr = callMatch[2];

    // Map DSL functions to GLSL functions
    const glslFuncMap = {
      'sphere': 'g_sdSphere',
      'box': 'g_sdBox',
      'subtract': 'g_opSubtract',
      'union': 'min',
      'smoothUnion': 'g_opSmoothUnion',
      'capsule': 'g_sdCapsule',
      'plane': 'g_sdPlane',
      'torus': 'g_sdTorus',
      'cylinder': 'g_sdCylinder',
      'cone': 'g_sdCone'
    };

    const glslFunc = glslFuncMap[funcName] || funcName;

    // Parse arguments
    const args = parseTemplateArgs(argsStr);

    // Generate GLSL based on function type
    if (funcName === 'sphere') {
      const r = args.r || args.radius || '1.0';
      const center = args.center || '[0.0, 0.0, 0.0]';
      const color = args.color || '[1.0, 1.0, 1.0]';
      const centerVec = compileValueToGLSL(center, templateParams);
      const colorVec = compileValueToGLSL(color, templateParams);
      return `vec4(${glslFunc}(p - ${centerVec}, ${r}), ${colorVec})`;
    } else if (funcName === 'box') {
      const size = args.size || args.s || '[1.0, 1.0, 1.0]';
      const center = args.center || '[0.0, 0.0, 0.0]';
      const color = args.color || '[1.0, 1.0, 1.0]';
      const sizeVec = compileValueToGLSL(size, templateParams);
      const centerVec = compileValueToGLSL(center, templateParams);
      const colorVec = compileValueToGLSL(color, templateParams);
      return `vec4(${glslFunc}(p - ${centerVec}, ${sizeVec}), ${colorVec})`;
    } else if (funcName === 'subtract') {
      const a = args.a;
      const b = args.b;
      return `vec4(${glslFunc}(${a}.x, ${b}.x), ${a}.yzw)`;
    } else {
      // Generic fallback
      return `vec4(9999.0, 1.0, 1.0, 1.0) /* Unknown: ${funcName} */`;
    }
  }

  // Helper to parse template function arguments
  function parseTemplateArgs(argsStr) {
    const args = {};
    const parts = splitArgs(argsStr);
    parts.forEach(part => {
      const eqIdx = part.indexOf('=');
      if (eqIdx !== -1) {
        const key = part.slice(0, eqIdx).trim();
        const val = part.slice(eqIdx + 1).trim();
        args[key] = val;
      }
    });
    return args;
  }

  // Helper to compile a value (array or expression) to GLSL
  function compileValueToGLSL(value, templateParams) {
    // Array literal: [x, y, z]
    if (value.startsWith('[') && value.endsWith(']')) {
      const inner = value.slice(1, -1);
      const parts = inner.split(',').map(p => {
        const trimmed = p.trim();
        // Convert time to u_time in array elements
        return exprToGLSL(trimmed, trimmed);
      });
      return `vec3(${parts.join(', ')})`;
    }
    // Template parameter or expression - convert time to u_time
    return exprToGLSL(value, value);
  }

  // Build set of intermediate template nodes to skip
  const templateIntermediateNodes = new Set();
  sg.forEach(node => {
    if (node && node._template && templatesToOptimize.has(node._template.template)) {
      // This is a template root node (e.g., i1)
      // Mark all nodes with IDs starting with this prefix as intermediate nodes
      const prefix = node.id + '_';
      sg.forEach(n => {
        if (n && n.id && n.id.startsWith(prefix)) {
          templateIntermediateNodes.add(n.id);
        }
      });
    }
  });

  ordered.forEach((node, idx) => {
    if (!node || !node.id) return;

    // Skip template definition nodes (already processed above)
    if (node._isTemplate) return;

    // Skip intermediate template nodes (e.g., i1_body, i1_eye1)
    if (templateIntermediateNodes.has(node.id)) {
      lines.push(`// Skipping intermediate template node: ${node.id}`);
      lines.push(``);
      return;
    }

    // Check if this node is a template instance that should use optimized function
    if (node._template && templatesToOptimize.has(node._template.template)) {
      const templateName = node._template.template;
      const fn = funcNameById.get(node.id);
      const params = node._template.params;

      lines.push(`// node ${idx}: template instance of '${templateName}' id=${node.id}`);
      lines.push(`vec4 ${fn}(vec3 p) {`);

      // Generate function call with template parameters
      const paramValues = Object.keys(params).map(paramName => {
        const paramValue = params[paramName];
        // Compile parameter values to GLSL
        if (paramValue.startsWith('[') && paramValue.endsWith(']')) {
          return compileValueToGLSL(paramValue, []);
        }
        return exprToGLSL(paramValue, paramValue);
      });

      lines.push(`  return template_${templateName}(p${paramValues.length > 0 ? ', ' + paramValues.join(', ') : ''});`);
      lines.push(`}`);
      lines.push(``);
      return;
    }

    const fn = funcNameById.get(node.id);
    const type = node.type || "unknown";
    const params = node.params || {};

    const col = vec3Expr(params.color || ["1.0", "1.0", "1.0"], "1.0", "color");
    const off = vec3Expr(params.offset || params.center || ["0.0", "0.0", "0.0"], "0.0", "offset");
    const rot = vec3Expr(params.rot || ["0.0", "0.0", "0.0"], "0.0", "rot");
    const hasQuat = params.rotq != null;

    lines.push("// node " + idx + ": type=" + type + " id=" + node.id);
    lines.push("vec4 " + fn + "(vec3 p) {");
    lines.push("  vec3 q = p;");
    lines.push("  q -= " + off + ";");
    if (hasQuat) {
      const rotqExpr = exprToGLSL(params.rotq, "vec4(0.0,0.0,0.0,1.0)");
      lines.push("  vec4 qrot = " + rotqExpr + ";");
      lines.push("  qrot = normalize(qrot);");
      lines.push("  q = g_qrotate(q, qrot);");
    } else {
      lines.push("  q = g_rotateXYZ(q, " + rot + ");");
    }

    if (type === "sphere") {
      const rExpr = exprToGLSL(params.radius, "1.0");
      lines.push("  float d = g_sdSphere(q, " + rExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "box") {
      const sExpr = params.size;
      let sizeExpr;
      if (Array.isArray(sExpr)) {
        sizeExpr = vec3Expr(sExpr, "1.0", "size");
      } else {
        const v = exprToGLSL(sExpr, "1.0");
        sizeExpr = "vec3(" + v + ")";
      }
      lines.push("  float d = g_sdBox(q, " + sizeExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "capsule") {
      const aExpr = vec3Expr(params.a, "0.0", "a");
      const bExpr = vec3Expr(params.b, "1.0", "b");
      const rExpr = exprToGLSL(params.r, "0.5");
      lines.push("  float d = g_sdCapsule(q, " + aExpr + ", " + bExpr + ", " + rExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "ellipsoid") {
      const rVec = Array.isArray(params.r)
        ? vec3Expr(params.r, "1.0", "r")
        : "vec3(" + exprToGLSL(params.r, "1.0") + ")";
      lines.push("  float d = g_sdEllipsoid(q, " + rVec + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "plane") {
      const nExpr = vec3Expr(params.n, "0.0", "n");
      const dExpr = exprToGLSL(params.d, "0.0");
      lines.push("  float d = g_sdPlane(q, " + nExpr + ", " + dExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "torus") {
      const majorRExpr = exprToGLSL(params.majorR || params.r1, "1.0");
      const minorRExpr = exprToGLSL(params.minorR || params.r2, "0.3");
      lines.push("  float d = g_sdTorus(q, " + majorRExpr + ", " + minorRExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "cylinder") {
      const rExpr = exprToGLSL(params.r || params.radius, "0.5");
      const hExpr = exprToGLSL(params.h || params.height, "1.0");
      lines.push("  float d = g_sdCylinder(q, " + rExpr + ", " + hExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "cone") {
      const rExpr = exprToGLSL(params.r || params.radius, "1.0");
      const hExpr = exprToGLSL(params.h || params.height, "1.0");
      lines.push("  float d = g_sdCone(q, " + rExpr + ", " + hExpr + ");");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    } else if (type === "union") {
      const calls = getInputCalls(node);
      if (!calls.length) {
        lines.push("  return vec4(9999.0, " + col + ");");
      } else {
        calls.forEach((c, i) => lines.push("  vec4 v" + i + " = " + c + ";"));
        lines.push("  vec4 best = v0;");
        for (let i = 1; i < calls.length; i++) {
          lines.push("  if (v" + i + ".x < best.x) best = v" + i + ";");
        }
        lines.push("  return best;");
      }
    } else if (type === "subtract") {
      const calls = getInputCalls(node);
      if (!calls.length) {
        lines.push("  return vec4(9999.0, " + col + ");");
      } else {
        calls.forEach((c, i) => lines.push("  vec4 v" + i + " = " + c + ";"));
        lines.push("  float d = v0.x;");
        for (let i = 1; i < calls.length; i++) {
          lines.push("  d = g_opSubtract(d, v" + i + ".x);");
        }
        lines.push("  return vec4(d, v0.yzw);");
      }
    } else if (type === "smoothUnion") {
      const calls = getInputCalls(node);
      const kExpr = exprToGLSL(params.k, "0.2");
      if (!calls.length) {
        lines.push("  return vec4(9999.0, " + col + ");");
      } else {
        calls.forEach((c, i) => lines.push("  vec4 v" + i + " = " + c + ";"));
        lines.push("  float d = v0.x;");
        for (let i = 1; i < calls.length; i++) {
          lines.push("  d = g_opSmoothUnion(d, v" + i + ".x, " + kExpr + ");");
        }
        lines.push("  vec4 best = v0;");
        for (let i = 1; i < calls.length; i++) {
          lines.push("  if (v" + i + ".x < best.x) best = v" + i + ";");
        }
        lines.push("  return vec4(d, best.yzw);");
      }
    } else if (type === "smoothSubtract") {
      const calls = getInputCalls(node);
      const kExpr = exprToGLSL(params.k, "0.2");
      if (!calls.length) {
        lines.push("  return vec4(9999.0, " + col + ");");
      } else {
        calls.forEach((c, i) => lines.push("  vec4 v" + i + " = " + c + ";"));
        lines.push("  float d = v0.x;");
        for (let i = 1; i < calls.length; i++) {
          lines.push("  d = g_opSmoothSubtract(d, v" + i + ".x, " + kExpr + ");");
        }
        lines.push("  return vec4(d, v0.yzw);");
      }
    } else if (type === "alias") {
      const calls = getInputCalls(node);
      if (!calls.length) {
        lines.push("  return vec4(9999.0, " + col + ");");
      } else {
        lines.push("  vec4 v0 = " + calls[0] + ";");
        lines.push("  return v0;");
      }
    } else {
      lines.push("  float d = 9999.0;");
      lines.push("  vec3 color = clamp(" + col + ", 0.0, 1.0);");
      lines.push("  return vec4(d, color);");
    }
    lines.push("}");
    lines.push("");
  });

  let root = ordered.find(n => n.id === "out");
  if (!root && ordered.length) root = ordered[ordered.length - 1];
  const rootFn = root ? funcNameById.get(root.id) : null;

  lines.push("vec4 g_df_scene(vec3 p) {");
  if (!rootFn) {
    lines.push("  return vec4(9999.0, 1.0, 1.0, 1.0);");
  } else {
    lines.push("  return " + rootFn + "(p);");
  }
  lines.push("}");
  lines.push("");
  lines.push("vec4 sampleGraphScene(vec3 p, out float sdf, out vec3 surfCol) {");
  lines.push("  vec4 v = g_df_scene(p);");
  lines.push("  float d = v.x;");
  lines.push("  vec3 col = v.yzw;");
  lines.push("  float den = smoothstep(0.1, -0.1, d);");
  lines.push("  sdf = d;");
  lines.push("  surfCol = col;");
  lines.push("  return vec4(col, den);");
  lines.push("}");

  return lines.join("\n");
}

// ============================================================
// DSL / GLSL preview component (uses legacy IR; runs shadow parser)
// ============================================================

