// Writes the city's design data as code for both sides: src/gen/design.js (page) and src/gen/design.wgsl
// (shaders), from src/design/*.json. Run by tools/assemble.py before it builds dist/city.html.
//   node drift-city/tools/gen-design.mjs
// Why: numbers that describe the city (where the landmarks stand, how tall they are) were written twice, once in
// world.js and once in scene.wgsl, with comments asking to keep them in step. Now they are written once, as data,
// and the build turns them into constants: no runtime cost, and the shader compiler folds them as before.
import fs from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const src = join(dirname(fileURLToPath(import.meta.url)), '..', 'src');
const L = JSON.parse(fs.readFileSync(join(src, 'design', 'landmarks.json'), 'utf8'));
const f = (x) => (Number.isInteger(x) ? x.toFixed(1) : String(+x.toFixed(6)));
const bl = Math.hypot(...L.beam.dir), beam = L.beam.dir.map((x) => x / bl);
const fabW = [(L.fab.block[0] + 0.5) * L.BIG, (L.fab.block[1] + 0.5) * L.BIG];
const head = (c) => `${c} GENERATED by drift-city/tools/gen-design.mjs from drift-city/src/design/landmarks.json. Do not edit: edit the JSON.\n`;

const wgsl = head('//') + [
  `const HALL_B: vec2i = vec2i(${L.hall.block.join(', ')});`,
  `const HALL_TOP: f32 = ${f(L.hall.top)};`,
  `const HALL_MAXD: f32 = ${f(L.hall.maxDist)};`,
  `const HIVE_B0: vec2i = vec2i(${L.hive.blocksX[0]}, ${L.hive.blocksZ[0]});`,
  `const HIVE_B1: vec2i = vec2i(${L.hive.blocksX[1]}, ${L.hive.blocksZ[1]});`,
  `const HIVE_BOUND_TOP: f32 = ${f(L.hive.boundTop)};`,
  `const FAB_B: vec2i = vec2i(${L.fab.block.join(', ')});`,
  `const FAB_BOUND_TOP: f32 = ${f(L.fab.boundTop)};`,
  `const FAB_W: vec2f = vec2f(${fabW.map(f).join(', ')});`,
  `const SPIRE_B: vec2i = vec2i(${L.spire.block.join(', ')});`,
  `const BEAM_B: vec3f = vec3f(${beam.map(f).join(', ')});`,
].join('\n') + '\n';

const js = head('//') + `const DESIGN = ${JSON.stringify({ hall: L.hall, hive: L.hive, fab: L.fab, spire: L.spire, beamDir: beam, fabW })};\n`;

fs.mkdirSync(join(src, 'gen'), { recursive: true });
fs.writeFileSync(join(src, 'gen', 'design.wgsl'), wgsl);
fs.writeFileSync(join(src, 'gen', 'design.js'), js);
console.log('design: wrote src/gen/design.wgsl and src/gen/design.js');
