// GENERATED by tools/ingest-audio.mjs — hand-edits will be overwritten.
// Run the tool after adding files under audio/per-station/ or
// audio/generic/. Paths are relative to audio/.
//
// perStation: a station's own song, played when the flock is inside it
// (two visits in three — a generic track takes the third turn, against
// monotony). generic: the interior rotation for every other station
// (GEARS AND BIRDCALLS lives here too — it is not special).
export const TRACKS = {
  perStation: {
    BARBICAN: "per-station/barbican-telematics-for-the-ages-remastered.mp3",
    "CAMDEN TOWN": "per-station/camden-town-canary-2.mp3",
    "CANARY WHARF": "per-station/canary-wharf-whisper-choir-remastered-x2.mp3",
    EUSTON: "per-station/euston-night-mail-remastered.mp3",
    "GLOUCESTER ROAD": "per-station/gloucester-road-americana-d-remastered.mp3",
    "LEICESTER SQUARE": "per-station/leicester-square-subjunction-fn.mp3",
    "LONDON BRIDGE": "per-station/london-bridge-gogogo-remastered.mp3",
    MOORGATE: "per-station/moorgate-backlot-2.mp3",
    "NORTH GREENWICH": "per-station/north-greenwich-paper-plane.mp3",
    "PICCADILLY CIRCUS": "per-station/piccadilly-circus-wiggly-wiggle-remastered.mp3",
    "SOUTH KENSINGTON": "per-station/south-kensington-muntelo-remastered.mp3",
    "ST PAUL'S": "per-station/st-pauls-gregorians.mp3",
    STRATFORD: "per-station/stratford-candied-waters-remastered.mp3",
    TEMPLE: "per-station/temple-claudes-lament-redux-guest-vocal.mp3",
    WESTMINSTER: "per-station/westminster-spring.mp3",
    WHITECHAPEL: "per-station/whitechapel-candy-code-waiting.mp3"
  },
  generic: [
    "generic/aching-evocative-space-waltz.mp3",
    "generic/gears-and-birdcalls.mp3",
    "generic/hypnotic-sleepy-loops.mp3",
    "generic/the-alchemists-ball.mp3",
    "generic/the-stone-ostinato.mp3",
    "generic/the-weight-of-motion.mp3"
  ]
};
