// robbin-facts.js — one small true thing about a station or its
// doorstep, shown as the flock gathers there. Hand-curated from
// public knowledge (Wikipedia and friends), phrased for a bird's-eye
// postcard. Not every station has one — that keeps them precious.
// Legends are labelled as legends.

export const STATION_FACTS = {
  'BANK': "The Central line platforms curve hard here to thread between the Bank of England's vaults.",
  'MONUMENT': 'Joined to Bank below ground: one sprawling station wearing two names.',
  'ANGEL': 'Home to the longest escalator on the Underground — sixty unbroken metres.',
  'HAMPSTEAD': 'The deepest station on the network: platforms nearly sixty metres down.',
  'AMERSHAM': 'The highest station above sea level anywhere on the Underground.',
  'CHESHAM': 'The farthest station from central London — the network peters into the Chilterns here.',
  'MORDEN': 'The southernmost station on the whole Underground.',
  'EPPING': 'The Central line ends here, deep in Essex forest country.',
  'ALDGATE': 'Built over a burial pit from the Great Plague of 1665.',
  'BAKER STREET': "Opened in 1863 on the world's first underground railway; Sherlock Holmes lodged, fictionally, up the road.",
  'BRIXTON': 'Electric Avenue nearby was the first market street lit by electricity.',
  'MAIDA VALE': 'Opened in 1915 staffed entirely by women.',
  'COVENT GARDEN': 'Lift-only, and said to be haunted by the actor William Terriss.',
  'HOLBORN': 'Its disused Aldwych branch platform moonlights in countless films.',
  "KING'S CROSS ST PANCRAS": 'More Underground lines meet here than anywhere else — six of them.',
  'TOTTENHAM COURT ROAD': "Lined with Eduardo Paolozzi's glass mosaics.",
  'CHARING CROSS': 'Distances to London are measured from a point just outside.',
  'WESTMINSTER': 'A dramatic concrete cavern of a station, deep beneath the chimes of Big Ben.',
  'SLOANE SQUARE': 'The River Westbourne crosses the station in a big iron pipe above the platforms.',
  'EMBANKMENT': 'The old "Mind the gap" voice was restored here so the announcer\'s widow could keep hearing him.',
  'PIMLICO': 'The only Victoria line station with no interchange at all.',
  'STOCKWELL': "One end of the original 1890 deep-level tube — the world's first.",
  'KENNINGTON': 'The mysterious Kennington loop turns trains around beneath the streets.',
  'OVAL': 'Named for the cricket ground; the platform tiles play along.',
  'BALHAM': 'Immortalised by Peter Sellers as "Bal-ham, Gateway to the South".',
  'CLAPHAM COMMON': 'One of only two deep stations with a single narrow island platform between the tracks.',
  'CLAPHAM NORTH': 'The other of the two narrow island platforms — mind the edges, both of them.',
  'MOORGATE': 'Steam trains of the Metropolitan once ran right into the City here.',
  'LIVERPOOL STREET': 'Built beside the site of old Bedlam — the Bethlem hospital.',
  'BETHNAL GREEN': "The Young V&A — long the Museum of Childhood — is just up the road.",
  'CANARY WHARF': 'A cathedral of a station by Norman Foster — the busiest on a single line.',
  'NORTH GREENWICH': 'The Millennium Dome — now the O2 — landed on its doorstep.',
  'CANADA WATER': 'Named for the docks that once welcomed timber ships from Canada.',
  'ROTHERHITHE': "Beside Brunel's Thames Tunnel — the first tunnel under a navigable river anywhere.",
  'SURREY QUAYS': 'Once Surrey Docks; whalers sailed from here before the timber came.',
  'LONDON BRIDGE': 'The oldest railway terminus site in London — with the Shard grown right on top.',
  'BOROUGH': 'Borough Market next door has fed London for about a thousand years.',
  'ELEPHANT & CASTLE': 'Named after a coaching inn, not an elephant.',
  'WARREN STREET': 'The platform tiles form little mazes — a warren, of course.',
  'WALTHAMSTOW CENTRAL': 'End of the Victoria line — the first automatic passenger railway in the world.',
  'SEVEN SISTERS': 'Named for a ring of seven elms planted centuries ago.',
  'ARSENAL': 'The only station named after a football club — Gillespie Road until 1932.',
  'LEICESTER SQUARE': 'The shortest hop on the network starts here: 260 metres to Covent Garden.',
  'PICCADILLY CIRCUS': 'Entirely underground since 1928 — there is no station building at all.',
  'CHANCERY LANE': 'A secret wartime telephone exchange hides in the deep-level tunnels below.',
  "ST PAUL'S": 'Called Post Office until 1937; the cathedral dome rises just up the hill.',
  'MILE END': 'The only spot where deep tube and sub-surface trains meet across one platform.',
  'STRATFORD': "Rebuilt for the 2012 Olympics — now one of Britain's busiest stations.",
  'LEYTONSTONE': 'Alfred Hitchcock grew up here; mosaic tributes line the corridors.',
  'GANTS HILL': 'Its grand barrel-vaulted hall salutes the Moscow Metro of the 1930s.',
  'SOUTHGATE': "Charles Holden's 1933 flying saucer of a station, landed on the A1004.",
  'ARNOS GROVE': "Holden's drum-shaped ticket hall is a modernist icon.",
  'COCKFOSTERS': 'End of the line; the name — beloved of all — likely means the chief forester\'s house.',
  'WEMBLEY PARK': 'Gateway to the stadium — twin towers then, the great arch now.',
  'HARROW-ON-THE-HILL': 'The capital of Metro-land, where the railway sold countryside dreams.',
  'UXBRIDGE': 'The 1938 terminus keeps its stained glass and winged-wheel crests.',
  'HEATHROW TERMINALS 2 & 3': "In 1977 this became the world's first tube stop inside an airport.",
  'HEATHROW TERMINAL 4': 'Served by a one-way loop — trains only ever call travelling one direction.',
  'HEATHROW TERMINAL 5': 'The newest west end of the Piccadilly, opened 2008.',
  'HAMMERSMITH': 'Two stations, one name, glaring at each other across the road.',
  "EARL'S COURT": "The Underground's first escalator arrived here in 1911 — legend says a wooden-legged man rode it to reassure the public.",
  'GLOUCESTER ROAD': 'A spare platform here is kept as an art gallery.',
  'SOUTH KENSINGTON': 'A Victorian pedestrian tunnel runs from the platforms all the way to the museums.',
  'HYDE PARK CORNER': 'The old ticket hall above became a hotel dining room.',
  'WHITE CITY': 'Named for the 1908 Olympic stadium city next door, all white marble.',
  'EAST FINCHLEY': 'An archer statue on the roof fires his arrow down the tunnel toward the City.',
  'HIGHGATE': 'A ghost surface station sleeps in the woods above the platforms.',
  'MORNINGTON CRESCENT': 'Immortalised by the radio game whose only rule is getting here.',
  'CAMDEN TOWN': "The Northern line's great underground junction — four tunnels braid beneath the market.",
  'WATERLOO': 'The Waterloo & City — "the Drain" — shuttles the City from here in a single stop.',
  'SOUTHWARK': 'Its concourse glows behind a wall of six hundred blue glass panes.',
  'TOWER HILL': "A surviving chunk of Roman London's wall stands beside the entrance.",
  'MANSION HOUSE': 'Despite the name, it is not even the closest station to the Mansion House.',
  'BLACKFRIARS': 'The old stone destination wall upstairs still dreams of Venice and St Petersburg.',
  'PADDINGTON': 'A small bronze bear from darkest Peru waits under the clock next door.',
  'EDGWARE ROAD': 'Two separate stations here insist on sharing one name.',
  'MARYLEBONE': "Quiet enough that the Beatles fled through it in A Hard Day's Night.",
  'GOODGE STREET': "Eisenhower's wartime headquarters sat in the deep-level shelter below.",
  'HOLLOWAY ROAD': 'An experimental spiral escalator was buried here in 1906; bits survive in the museum depot.',
  'GOLDERS GREEN': 'Where the Northern line first burst out of the tunnels into open country, 1907.',
  'BELSIZE PARK': 'Another deep-level shelter hums below — its bunk-lined tunnels still tourable.',
  'OXFORD CIRCUS': 'Rebuilt around the running trains in the 1960s without ever closing.',
  'VAUXHALL': 'Legend has it this name became vokzal — Russian for railway station.',
  'BATTERSEA POWER STATION': 'Named for the giant brick cathedral of electricity it serves.',
  'WHITECHAPEL': 'The Underground runs above the Overground here — the depths swap places.',
  'UPMINSTER': "The District's far eastern end, out among the Essex fields.",
  'WIMBLEDON': "Tennis fortnight turns this terminus into centre court's front door.",
  'RICHMOND': 'The line ends beside Thames meadows and a deer park.',
  'KEW GARDENS': 'The only station with a pub attached straight onto the platform.',
  'KENSINGTON (OLYMPIA)': 'A part-time station that mostly wakes for the exhibition halls.',
  'ACTON TOWN': "The Underground's museum depot hoards its treasures nearby.",
  'EALING BROADWAY': 'The District line reached here in 1879 — the leafy Queen of the Suburbs.',
  'SUDBURY TOWN': 'Holden called his 1931 design "a brick box with a concrete lid". He meant it kindly.',
  'WATFORD': 'The Metropolitan\'s quiet cul-de-sac, nearly a mile from the town it names.',
  'STANMORE': "The Jubilee's northern end, at the foot of a wooded hill.",
  "ST JOHN'S WOOD": "The closest station to Abbey Road's famous zebra crossing.",
  'SWISS COTTAGE': 'Named after a chalet-styled pub that still stands outside.',
  'EUSTON': "The great Doric arch of old Euston stood here — London's lost gateway.",
  'TOOTING BROADWAY': '"Freedom for Tooting!" — Citizen Smith proclaimed it at this very corner.',
  'LAMBETH NORTH': "The Imperial War Museum's great naval guns aim over its roof.",
  'QUEENSBURY': 'A station that named its suburb, rather than the other way round.',
  'DOLLIS HILL': "Churchill's secret cabinet bunker, Paddock, hides up the hill.",
  'NEASDEN': "Private Eye's favourite punchline — and keeper of the depot.",
  'MILL HILL EAST': 'A one-station branch, left over from a grander plan.',
  'HIGH BARNET': 'The Northern line climbs out of London to this hilltop market town.',
};
