// GENERATED by tools/analyze-tracks.mjs — do not edit by hand.
// A MIDI-like, parameterized approximation of the three soundtrack
// recordings, analyzed from the audio itself (onset autocorrelation for
// tempo, per-bar chroma vs triad templates for harmony, chroma
// self-similarity for loop length, RMS for the energy arc):
//  · engines: 83 BPM, Em, 4-bar loop, build ×1.21
//  · gears: 102 BPM, Gm, 16-bar loop, build ×1.48
//  · passacaglia: 140 BPM, Dm, 12-bar loop, build ×1.23
// The ScorePlayer performs these live: loopable to the bar, responsive
// to flock size, rush hour and rescues. Approximation, not transcription.
export const SCORE = {
 "engines": {
  "bpm": 83,
  "duration": 59,
  "bars": 19,
  "loop": 4,
  "keyRoot": 4,
  "minorKey": true,
  "cycle": [
   {
    "root": 6,
    "minor": false
   },
   {
    "root": 11,
    "minor": false
   },
   {
    "root": 4,
    "minor": true
   },
   {
    "root": 4,
    "minor": true
   }
  ],
  "energy": [
   0.82,
   0.87,
   1,
   0.93
  ],
  "build": 1.21
 },
 "gears": {
  "bpm": 102,
  "duration": 98,
  "bars": 40,
  "loop": 16,
  "keyRoot": 7,
  "minorKey": true,
  "cycle": [
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 9,
    "minor": false
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 9,
    "minor": false
   },
   {
    "root": 3,
    "minor": false
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 3,
    "minor": false
   },
   {
    "root": 3,
    "minor": true
   },
   {
    "root": 3,
    "minor": false
   }
  ],
  "energy": [
   0.64,
   0.56,
   0.66,
   0.84,
   0.78,
   0.79,
   0.64,
   0.68,
   0.82,
   0.77,
   0.91,
   0.52,
   0.54,
   0.82,
   0.82,
   1
  ],
  "build": 1.48
 },
 "passacaglia": {
  "bpm": 140,
  "duration": 126,
  "bars": 72,
  "loop": 12,
  "keyRoot": 2,
  "minorKey": true,
  "cycle": [
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 2,
    "minor": true
   },
   {
    "root": 2,
    "minor": true
   },
   {
    "root": 7,
    "minor": true
   },
   {
    "root": 0,
    "minor": true
   },
   {
    "root": 5,
    "minor": false
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 2,
    "minor": false
   },
   {
    "root": 2,
    "minor": true
   }
  ],
  "energy": [
   0.88,
   0.96,
   0.9,
   0.86,
   0.84,
   0.93,
   0.96,
   0.99,
   0.86,
   0.85,
   0.94,
   1
  ],
  "build": 1.23
 }
};
