// GENERATED by tools/ingest-audio.mjs — hand-edits will be overwritten.
// Run the tool after adding files under audio/per-station/ or
// audio/generic/. Paths are relative to audio/.
//
// perStation: a station's own song, played when the flock is inside it
// (two visits in three — a generic track takes the third turn, against
// monotony). generic: the interior rotation for every other station
// (GEARS AND BIRDCALLS lives here too — it is not special).
export const TRACKS = {
  perStation: {
    "GLOUCESTER ROAD": "per-station/gloucester-road-americana-d-remastered.mp3",
    "LEICESTER SQUARE": "per-station/leicester-square-subjunction-fn.mp3",
    "LONDON BRIDGE": "per-station/london-bridge-gogogo-remastered.mp3",
    "SOUTH KENSINGTON": "per-station/south-kensington-muntelo-remastered.mp3",
    "ST PAUL'S": "per-station/st-pauls-gregorians.mp3"
  },
  generic: [
    "generic/aching-evocative-space-waltz.mp3",
    "generic/gears-and-birdcalls.mp3",
    "generic/hypnotic-sleepy-loops.mp3"
  ]
};
