// tube-network.js — the whole London Underground for TUBE FLOCK.
// GENERATED by tools/fetch-tube.mjs from the TfL Unified API — do not edit
// by hand; re-run the tool to refresh. Step-free list is curated (real-ish).
// Snapshot date: 2026-07-20 · relaid out 2026-07-21
// DLR grafted 2026-07-23 by tools/graft-dlr.mjs
// Windrush (full) + Elizabeth core grafted 2026-07-23
// by tools/graft-overground.mjs (existing positions untouched).

export const NETWORK = {
 "generated": "2026-07-20",
 "relaidOut": "2026-07-21",
 "dlrGrafted": "2026-07-23",
 "overgroundGrafted": "2026-07-23",
 "pos": {
  "HARROW & WEALDSTONE": [
   59.55,
   48.62
  ],
  "KENTON": [
   64.18,
   53.16
  ],
  "SOUTH KENTON": [
   65.27,
   57.82
  ],
  "NORTH WEMBLEY": [
   69.81,
   62.31
  ],
  "WEMBLEY CENTRAL": [
   70.93,
   66.61
  ],
  "STONEBRIDGE PARK": [
   75.47,
   70.94
  ],
  "HARLESDEN": [
   79.98,
   75.07
  ],
  "WILLESDEN JUNCTION": [
   84.36,
   78.96
  ],
  "KENSAL GREEN": [
   89.68,
   79.52
  ],
  "QUEEN'S PARK": [
   92.84,
   77.91
  ],
  "KILBURN PARK": [
   98.06,
   78.2
  ],
  "MAIDA VALE": [
   101.95,
   81.31
  ],
  "WARWICK AVENUE": [
   105.73,
   84.4
  ],
  "PADDINGTON": [
   109.39,
   87.29
  ],
  "EDGWARE ROAD": [
   112.2,
   85.11
  ],
  "MARYLEBONE": [
   114.5,
   82.89
  ],
  "BAKER STREET": [
   116.89,
   80.7
  ],
  "REGENT'S PARK": [
   122.08,
   86.03
  ],
  "OXFORD CIRCUS": [
   126.94,
   91.09
  ],
  "PICCADILLY CIRCUS": [
   129.92,
   95.46
  ],
  "CHARING CROSS": [
   133.2,
   98.36
  ],
  "EMBANKMENT": [
   136.51,
   99.69
  ],
  "WATERLOO": [
   140.04,
   102.75
  ],
  "LAMBETH NORTH": [
   140.84,
   106.25
  ],
  "ELEPHANT & CASTLE": [
   143.86,
   109.36
  ],
  "EPPING": [
   203.93,
   0.2
  ],
  "THEYDON BOIS": [
   203.79,
   9.44
  ],
  "DEBDEN": [
   203.51,
   18.69
  ],
  "LOUGHTON": [
   198.5,
   25.45
  ],
  "BUCKHURST HILL": [
   197.89,
   35.42
  ],
  "WOODFORD": [
   197.35,
   45.81
  ],
  "SOUTH WOODFORD": [
   196.82,
   50.66
  ],
  "SNARESBROOK": [
   196.15,
   55.82
  ],
  "LEYTONSTONE": [
   191.61,
   60.86
  ],
  "LEYTON": [
   184.04,
   67.94
  ],
  "STRATFORD": [
   182.09,
   75.21
  ],
  "MILE END": [
   172.89,
   83.19
  ],
  "BETHNAL GREEN": [
   161.5,
   83.77
  ],
  "LIVERPOOL STREET": [
   153.09,
   90.09
  ],
  "BANK": [
   149.44,
   93.45
  ],
  "ST PAUL'S": [
   145.36,
   93.11
  ],
  "CHANCERY LANE": [
   141.92,
   90.29
  ],
  "HOLBORN": [
   137.12,
   89.82
  ],
  "TOTTENHAM COURT ROAD": [
   132.31,
   90.56
  ],
  "BOND STREET": [
   119.69,
   91.06
  ],
  "MARBLE ARCH": [
   115.78,
   91.96
  ],
  "LANCASTER GATE": [
   112.25,
   92.68
  ],
  "QUEENSWAY": [
   108.78,
   93.39
  ],
  "NOTTING HILL GATE": [
   105.26,
   93.89
  ],
  "HOLLAND PARK": [
   99.44,
   93.62
  ],
  "SHEPHERD'S BUSH": [
   92.29,
   92.74
  ],
  "WHITE CITY": [
   86.45,
   87.65
  ],
  "EAST ACTON": [
   79.37,
   86.63
  ],
  "NORTH ACTON": [
   73.14,
   81
  ],
  "HANGER LANE": [
   64.78,
   81.39
  ],
  "PERIVALE": [
   60,
   78.51
  ],
  "GREENFORD": [
   55.53,
   75.37
  ],
  "NORTHOLT": [
   50.94,
   71.42
  ],
  "SOUTH RUISLIP": [
   46.31,
   66.53
  ],
  "RUISLIP GARDENS": [
   41.49,
   61.93
  ],
  "WEST RUISLIP": [
   36.58,
   57.12
  ],
  "HAINAULT": [
   205.63,
   48.41
  ],
  "FAIRLOP": [
   205.53,
   51.5
  ],
  "BARKINGSIDE": [
   205.32,
   54.69
  ],
  "NEWBURY PARK": [
   204.97,
   57.9
  ],
  "GANTS HILL": [
   201.66,
   58.17
  ],
  "REDBRIDGE": [
   198.15,
   58.41
  ],
  "WANSTEAD": [
   194.43,
   58.61
  ],
  "GRANGE HILL": [
   205.53,
   45.28
  ],
  "CHIGWELL": [
   203.13,
   43.21
  ],
  "RODING VALLEY": [
   199.86,
   43.44
  ],
  "WEST ACTON": [
   67.83,
   85.8
  ],
  "EALING BROADWAY": [
   60.62,
   85.98
  ],
  "BAYSWATER": [
   107.3,
   90.65
  ],
  "HIGH STREET KENSINGTON": [
   105.37,
   99.62
  ],
  "GLOUCESTER ROAD": [
   110.22,
   104.6
  ],
  "SOUTH KENSINGTON": [
   115.36,
   104.24
  ],
  "SLOANE SQUARE": [
   121.05,
   104.28
  ],
  "VICTORIA": [
   126.88,
   104.16
  ],
  "ST JAMES'S PARK": [
   130.31,
   103.98
  ],
  "WESTMINSTER": [
   133.16,
   102.02
  ],
  "TEMPLE": [
   139.23,
   97.51
  ],
  "BLACKFRIARS": [
   142.55,
   97.11
  ],
  "MANSION HOUSE": [
   145.86,
   96.82
  ],
  "CANNON STREET": [
   149.14,
   96.53
  ],
  "MONUMENT": [
   152.36,
   95.84
  ],
  "TOWER HILL": [
   155.54,
   95.18
  ],
  "ALDGATE": [
   155.5,
   92.15
  ],
  "MOORGATE": [
   148.98,
   88.05
  ],
  "BARBICAN": [
   144.29,
   85.08
  ],
  "FARRINGDON": [
   140.07,
   84
  ],
  "KING'S CROSS ST PANCRAS": [
   136.3,
   81.47
  ],
  "EUSTON SQUARE": [
   129.27,
   81.24
  ],
  "GREAT PORTLAND STREET": [
   123.23,
   81.07
  ],
  "ROYAL OAK": [
   105.77,
   87.88
  ],
  "WESTBOURNE PARK": [
   102.33,
   88.54
  ],
  "LADBROKE GROVE": [
   99.56,
   90.71
  ],
  "LATIMER ROAD": [
   96.37,
   94.08
  ],
  "WOOD LANE": [
   94.03,
   96.84
  ],
  "SHEPHERD'S BUSH MARKET": [
   93.32,
   100.22
  ],
  "GOLDHAWK ROAD": [
   92.76,
   103.6
  ],
  "HAMMERSMITH": [
   92.17,
   106.93
  ],
  "UPMINSTER": [
   260,
   75.83
  ],
  "UPMINSTER BRIDGE": [
   254.29,
   75.86
  ],
  "HORNCHURCH": [
   250.44,
   78.47
  ],
  "ELM PARK": [
   244.51,
   78.63
  ],
  "DAGENHAM EAST": [
   238.45,
   78.71
  ],
  "DAGENHAM HEATHWAY": [
   232.23,
   78.79
  ],
  "BECONTREE": [
   225.79,
   78.89
  ],
  "UPNEY": [
   219.07,
   78.99
  ],
  "BARKING": [
   212.02,
   79.09
  ],
  "EAST HAM": [
   204.57,
   79.19
  ],
  "UPTON PARK": [
   197.03,
   79.36
  ],
  "PLAISTOW": [
   191.15,
   82.42
  ],
  "WEST HAM": [
   183.23,
   82.71
  ],
  "BROMLEY-BY-BOW": [
   179.94,
   82.91
  ],
  "BOW ROAD": [
   176.53,
   83.06
  ],
  "STEPNEY GREEN": [
   169.14,
   86.28
  ],
  "WHITECHAPEL": [
   164.31,
   87.23
  ],
  "ALDGATE EAST": [
   160,
   90.38
  ],
  "EARL'S COURT": [
   104.65,
   105.73
  ],
  "WEST KENSINGTON": [
   101.06,
   105.97
  ],
  "BARONS COURT": [
   97.52,
   106.25
  ],
  "RAVENSCOURT PARK": [
   88.88,
   107
  ],
  "STAMFORD BROOK": [
   85.49,
   107.04
  ],
  "TURNHAM GREEN": [
   82.15,
   106.95
  ],
  "CHISWICK PARK": [
   78.27,
   103.62
  ],
  "ACTON TOWN": [
   74.2,
   99.79
  ],
  "EALING COMMON": [
   68.59,
   93.89
  ],
  "GUNNERSBURY": [
   74.06,
   108.9
  ],
  "KEW GARDENS": [
   72.42,
   117.52
  ],
  "RICHMOND": [
   64.93,
   125.36
  ],
  "WEST BROMPTON": [
   104.56,
   113.43
  ],
  "FULHAM BROADWAY": [
   104.5,
   120.73
  ],
  "PARSONS GREEN": [
   101.36,
   125.4
  ],
  "PUTNEY BRIDGE": [
   98.2,
   129.93
  ],
  "EAST PUTNEY": [
   98.11,
   137.11
  ],
  "SOUTHFIELDS": [
   98.17,
   144.2
  ],
  "WIMBLEDON PARK": [
   101.39,
   148.95
  ],
  "WIMBLEDON": [
   101.55,
   156.2
  ],
  "KENSINGTON (OLYMPIA)": [
   100.66,
   101.67
  ],
  "CANNING TOWN": [
   181.78,
   89.75
  ],
  "NORTH GREENWICH": [
   180.42,
   96.59
  ],
  "CANARY WHARF": [
   172.33,
   97.97
  ],
  "CANADA WATER": [
   164.65,
   104.87
  ],
  "BERMONDSEY": [
   155.98,
   105.15
  ],
  "LONDON BRIDGE": [
   150.13,
   101.54
  ],
  "SOUTHWARK": [
   145.49,
   102.12
  ],
  "GREEN PARK": [
   126.88,
   97.59
  ],
  "ST JOHN'S WOOD": [
   113.05,
   76.84
  ],
  "SWISS COTTAGE": [
   112.03,
   72.94
  ],
  "FINCHLEY ROAD": [
   107.43,
   72.33
  ],
  "WEST HAMPSTEAD": [
   104.7,
   72.02
  ],
  "KILBURN": [
   101.98,
   71.85
  ],
  "WILLESDEN GREEN": [
   99.22,
   71.7
  ],
  "DOLLIS HILL": [
   96.39,
   72.58
  ],
  "NEASDEN": [
   93.36,
   73.18
  ],
  "WEMBLEY PARK": [
   94.13,
   70.23
  ],
  "KINGSBURY": [
   93.04,
   60.01
  ],
  "QUEENSBURY": [
   92.44,
   50
  ],
  "CANONS PARK": [
   92.04,
   40.55
  ],
  "STANMORE": [
   91.84,
   31.47
  ],
  "AMERSHAM": [
   0,
   8.4
  ],
  "CHALFONT & LATIMER": [
   12,
   8.2
  ],
  "CHORLEYWOOD": [
   20.95,
   15.96
  ],
  "RICKMANSWORTH": [
   30.03,
   23.54
  ],
  "MOOR PARK": [
   41.95,
   24.48
  ],
  "NORTHWOOD": [
   42.19,
   34.92
  ],
  "NORTHWOOD HILLS": [
   47.53,
   42.01
  ],
  "PINNER": [
   53.37,
   49.04
  ],
  "NORTH HARROW": [
   59.77,
   56.4
  ],
  "HARROW-ON-THE-HILL": [
   67,
   64.34
  ],
  "NORTHWICK PARK": [
   76.22,
   64.83
  ],
  "PRESTON ROAD": [
   86.03,
   65.45
  ],
  "CHESHAM": [
   3.53,
   0
  ],
  "WEST HARROW": [
   56.9,
   64.35
  ],
  "RAYNERS LANE": [
   50.88,
   68.4
  ],
  "EASTCOTE": [
   44.76,
   69.3
  ],
  "RUISLIP MANOR": [
   40.46,
   72.18
  ],
  "RUISLIP": [
   36.43,
   75.3
  ],
  "ICKENHAM": [
   32.53,
   78.51
  ],
  "HILLINGDON": [
   28.73,
   81.84
  ],
  "UXBRIDGE": [
   25.02,
   85.28
  ],
  "CROXLEY": [
   42.15,
   21.21
  ],
  "WATFORD": [
   44.5,
   18.73
  ],
  "HIGH BARNET": [
   101.4,
   21.07
  ],
  "TOTTERIDGE & WHETSTONE": [
   103.78,
   23.65
  ],
  "WOODSIDE PARK": [
   101.95,
   26.34
  ],
  "WEST FINCHLEY": [
   101.9,
   29.73
  ],
  "FINCHLEY CENTRAL": [
   99.77,
   32.33
  ],
  "EAST FINCHLEY": [
   106.99,
   39.49
  ],
  "HIGHGATE": [
   113.78,
   46.27
  ],
  "ARCHWAY": [
   120.05,
   52.67
  ],
  "TUFNELL PARK": [
   121.28,
   59.66
  ],
  "KENTISH TOWN": [
   122.25,
   66.59
  ],
  "CAMDEN TOWN": [
   123.16,
   73.51
  ],
  "MORNINGTON CRESCENT": [
   127.55,
   77.76
  ],
  "EUSTON": [
   132.09,
   82.1
  ],
  "WARREN STREET": [
   128.39,
   85.53
  ],
  "GOODGE STREET": [
   130.36,
   88.08
  ],
  "LEICESTER SQUARE": [
   132.62,
   93.95
  ],
  "KENNINGTON": [
   140.58,
   112.86
  ],
  "OVAL": [
   137.84,
   118.08
  ],
  "STOCKWELL": [
   137.89,
   124.15
  ],
  "CLAPHAM NORTH": [
   133.72,
   129.29
  ],
  "CLAPHAM COMMON": [
   129.81,
   134.08
  ],
  "CLAPHAM SOUTH": [
   126.12,
   138.69
  ],
  "BALHAM": [
   125.71,
   144.86
  ],
  "TOOTING BEC": [
   122.46,
   149.16
  ],
  "TOOTING BROADWAY": [
   119.3,
   153.21
  ],
  "COLLIERS WOOD": [
   116.3,
   157.1
  ],
  "SOUTH WIMBLEDON": [
   113.49,
   160.88
  ],
  "MORDEN": [
   113.33,
   166.53
  ],
  "ANGEL": [
   142.55,
   81.96
  ],
  "OLD STREET": [
   146.97,
   85.65
  ],
  "BOROUGH": [
   147.09,
   105.49
  ],
  "EDGWARE": [
   80.76,
   34.26
  ],
  "BURNT OAK": [
   85.87,
   39.39
  ],
  "COLINDALE": [
   90.85,
   44.38
  ],
  "HENDON CENTRAL": [
   95.66,
   49.22
  ],
  "BRENT CROSS": [
   100.29,
   53.87
  ],
  "GOLDERS GREEN": [
   105.17,
   54.92
  ],
  "HAMPSTEAD": [
   109.82,
   59.55
  ],
  "BELSIZE PARK": [
   114.33,
   64.23
  ],
  "CHALK FARM": [
   118.77,
   68.9
  ],
  "MILL HILL EAST": [
   97.32,
   29.77
  ],
  "NINE ELMS": [
   134.56,
   117.55
  ],
  "BATTERSEA POWER STATION": [
   126.54,
   117.86
  ],
  "COCKFOSTERS": [
   126.29,
   27.66
  ],
  "OAKWOOD": [
   130.1,
   27.97
  ],
  "SOUTHGATE": [
   130.89,
   31.35
  ],
  "ARNOS GROVE": [
   131.57,
   35.4
  ],
  "BOUNDS GREEN": [
   135.54,
   39.77
  ],
  "WOOD GREEN": [
   139.87,
   44.6
  ],
  "TURNPIKE LANE": [
   144.38,
   49.87
  ],
  "MANOR HOUSE": [
   144.99,
   57.54
  ],
  "FINSBURY PARK": [
   145.45,
   65.77
  ],
  "ARSENAL": [
   142.85,
   68.87
  ],
  "HOLLOWAY ROAD": [
   139.97,
   72.38
  ],
  "CALEDONIAN ROAD": [
   136.78,
   76.26
  ],
  "RUSSELL SQUARE": [
   136.8,
   85.88
  ],
  "COVENT GARDEN": [
   135.1,
   92.06
  ],
  "HYDE PARK CORNER": [
   123.28,
   100.9
  ],
  "KNIGHTSBRIDGE": [
   118.82,
   101.43
  ],
  "NORTH EALING": [
   67.88,
   88.91
  ],
  "PARK ROYAL": [
   67.26,
   82.92
  ],
  "ALPERTON": [
   63.19,
   78.75
  ],
  "SUDBURY TOWN": [
   59.63,
   75.33
  ],
  "SUDBURY HILL": [
   56.72,
   72.58
  ],
  "SOUTH HARROW": [
   53.96,
   70.58
  ],
  "SOUTH EALING": [
   67.94,
   100.58
  ],
  "NORTHFIELDS": [
   62.91,
   104.02
  ],
  "BOSTON MANOR": [
   58.03,
   107.56
  ],
  "OSTERLEY": [
   53.19,
   111.02
  ],
  "HOUNSLOW EAST": [
   48.34,
   114.33
  ],
  "HOUNSLOW CENTRAL": [
   42.01,
   114.95
  ],
  "HOUNSLOW WEST": [
   35.55,
   115.3
  ],
  "HATTON CROSS": [
   29.02,
   115.58
  ],
  "HEATHROW TERMINALS 2 & 3": [
   21.99,
   115.7
  ],
  "HEATHROW TERMINAL 5": [
   15.19,
   115.77
  ],
  "HEATHROW TERMINAL 4": [
   21.9,
   122.87
  ],
  "WALTHAMSTOW CENTRAL": [
   179.92,
   53.44
  ],
  "BLACKHORSE ROAD": [
   170.11,
   53.63
  ],
  "TOTTENHAM HALE": [
   160.26,
   53.98
  ],
  "SEVEN SISTERS": [
   152.91,
   59.6
  ],
  "HIGHBURY & ISLINGTON": [
   143.89,
   73.91
  ],
  "PIMLICO": [
   132,
   109.85
  ],
  "VAUXHALL": [
   136.87,
   115.22
  ],
  "BRIXTON": [
   145.31,
   131.84
  ],
  "ROTHERHITHE": [
   162.34,
   102.44
  ],
  "SURREY QUAYS": [
   164.96,
   111.23
  ],
  "LEWISHAM": [
   176.9,
   122.73
  ],
  "ELVERSON ROAD": [
   175.41,
   120.19
  ],
  "DEPTFORD BRIDGE": [
   173.23,
   117.21
  ],
  "GREENWICH": [
   176.25,
   115.12
  ],
  "CUTTY SARK (FOR MARITIME GREENWICH)": [
   177.18,
   113.13
  ],
  "ISLAND GARDENS": [
   177.25,
   109.66
  ],
  "MUDCHUTE": [
   175.53,
   107.97
  ],
  "CROSSHARBOUR": [
   175.44,
   105.12
  ],
  "SOUTH QUAY": [
   174.78,
   102.66
  ],
  "HERON QUAYS": [
   172.51,
   101.66
  ],
  "WEST INDIA QUAY": [
   170.39,
   99.22
  ],
  "POPLAR": [
   171.13,
   96.56
  ],
  "ALL SAINTS": [
   175,
   95.14
  ],
  "LANGDON PARK": [
   174.77,
   90.89
  ],
  "DEVONS ROAD": [
   174.84,
   86.28
  ],
  "BOW CHURCH": [
   175.51,
   81.71
  ],
  "PUDDING MILL LANE": [
   178.86,
   78.53
  ],
  "WESTFERRY": [
   166.66,
   96.53
  ],
  "LIMEHOUSE": [
   160.75,
   95.1
  ],
  "SHADWELL": [
   155,
   93.72
  ],
  "TOWER GATEWAY": [
   154.05,
   96
  ],
  "BECKTON": [
   202.18,
   95.58
  ],
  "GALLIONS REACH": [
   205.68,
   98.55
  ],
  "CYPRUS": [
   203.09,
   98.83
  ],
  "BECKTON PARK": [
   199.88,
   98.55
  ],
  "ROYAL ALBERT": [
   196.34,
   98.61
  ],
  "PRINCE REGENT": [
   191.91,
   97.3
  ],
  "CUSTOM HOUSE (FOR EXCEL)": [
   187.71,
   96.39
  ],
  "ROYAL VICTORIA": [
   184.12,
   93.71
  ],
  "EAST INDIA": [
   179.33,
   93.69
  ],
  "BLACKWALL": [
   175.77,
   96.65
  ],
  "WOOLWICH ARSENAL": [
   200.46,
   104.15
  ],
  "KING GEORGE V": [
   196.7,
   101.42
  ],
  "LONDON CITY AIRPORT": [
   192.92,
   98.66
  ],
  "PONTOON DOCK": [
   189.24,
   95.67
  ],
  "WEST SILVERTOWN": [
   185.51,
   92.72
  ],
  "STAR LANE": [
   181.17,
   86.82
  ],
  "ABBEY ROAD": [
   181.14,
   84.12
  ],
  "STRATFORD HIGH STREET": [
   180.57,
   79.55
  ],
  "STRATFORD INTERNATIONAL": [
   177.7,
   76.57
  ],
  "WEST CROYDON": [
   146.12,
   156.17
  ],
  "NORWOOD JUNCTION": [
   148.28,
   151.89
  ],
  "ANERLEY": [
   150.46,
   147.43
  ],
  "PENGE WEST": [
   152.66,
   142.8
  ],
  "SYDENHAM": [
   154.41,
   137.79
  ],
  "FOREST HILL": [
   156.48,
   132.63
  ],
  "HONOR OAK PARK": [
   158.56,
   127.38
  ],
  "BROCKLEY": [
   160.67,
   122.05
  ],
  "NEW CROSS GATE": [
   162.78,
   116.67
  ],
  "WAPPING": [
   158.62,
   98.03
  ],
  "SHOREDITCH HIGH STREET": [
   159.83,
   86.16
  ],
  "HOXTON": [
   155.6,
   84.35
  ],
  "HAGGERSTON": [
   152.5,
   80.95
  ],
  "DALSTON JUNCTION": [
   151.06,
   76.58
  ],
  "CANONBURY": [
   147,
   74.41
  ],
  "CLAPHAM JUNCTION": [
   135.83,
   119.63
  ],
  "WANDSWORTH ROAD": [
   140.5,
   118.65
  ],
  "CLAPHAM HIGH STREET": [
   145.22,
   117.26
  ],
  "DENMARK HILL": [
   150.04,
   115.78
  ],
  "PECKHAM RYE": [
   154.96,
   114.27
  ],
  "QUEENS ROAD PECKHAM": [
   159.94,
   112.76
  ],
  "CRYSTAL PALACE": [
   151.55,
   141.52
  ],
  "NEW CROSS": [
   163.74,
   115.27
  ],
  "WOOLWICH": [
   191.25,
   99.33
  ],
  "ABBEY WOOD": [
   195.59,
   100.13
  ]
 },
 "thames": [
  [
   59.06,
   157.15
  ],
  [
   59.71,
   157.15
  ],
  [
   60.99,
   157.14
  ],
  [
   62.91,
   157.12
  ],
  [
   65.47,
   157.1
  ],
  [
   67.03,
   156.52
  ],
  [
   67.59,
   155.38
  ],
  [
   67.14,
   153.67
  ],
  [
   65.7,
   151.4
  ],
  [
   64.34,
   149.09
  ],
  [
   63.06,
   146.76
  ],
  [
   61.88,
   144.38
  ],
  [
   60.79,
   141.98
  ],
  [
   60.05,
   139.69
  ],
  [
   59.67,
   137.52
  ],
  [
   59.65,
   135.47
  ],
  [
   59.98,
   133.54
  ],
  [
   60.5,
   131.84
  ],
  [
   61.22,
   130.37
  ],
  [
   62.12,
   129.12
  ],
  [
   63.21,
   128.1
  ],
  [
   63.79,
   126.85
  ],
  [
   63.86,
   125.36
  ],
  [
   63.42,
   123.63
  ],
  [
   62.47,
   121.67
  ],
  [
   62.11,
   119.81
  ],
  [
   62.34,
   118.07
  ],
  [
   63.16,
   116.44
  ],
  [
   64.57,
   114.92
  ],
  [
   65.92,
   113.55
  ],
  [
   67.22,
   112.33
  ],
  [
   68.46,
   111.27
  ],
  [
   69.64,
   110.36
  ],
  [
   70.93,
   109.81
  ],
  [
   72.32,
   109.63
  ],
  [
   73.82,
   109.81
  ],
  [
   75.42,
   110.35
  ],
  [
   76.96,
   111.48
  ],
  [
   78.44,
   113.21
  ],
  [
   79.87,
   115.53
  ],
  [
   81.23,
   118.45
  ],
  [
   82.56,
   120.46
  ],
  [
   83.85,
   121.56
  ],
  [
   85.1,
   121.76
  ],
  [
   86.31,
   121.06
  ],
  [
   87.44,
   119.93
  ],
  [
   88.49,
   118.38
  ],
  [
   89.46,
   116.41
  ],
  [
   90.35,
   114.02
  ],
  [
   91.32,
   112.71
  ],
  [
   92.38,
   112.5
  ],
  [
   93.53,
   113.38
  ],
  [
   94.77,
   115.35
  ],
  [
   95.78,
   117.83
  ],
  [
   96.57,
   120.82
  ],
  [
   97.13,
   124.32
  ],
  [
   97.47,
   128.34
  ],
  [
   98.21,
   131.44
  ],
  [
   99.34,
   133.63
  ],
  [
   100.87,
   134.91
  ],
  [
   102.79,
   135.28
  ],
  [
   104.66,
   135.05
  ],
  [
   106.48,
   134.22
  ],
  [
   108.25,
   132.79
  ],
  [
   109.97,
   130.76
  ],
  [
   111.39,
   128.59
  ],
  [
   112.51,
   126.28
  ],
  [
   113.34,
   123.83
  ],
  [
   113.87,
   121.23
  ],
  [
   114.72,
   119.02
  ],
  [
   115.88,
   117.21
  ],
  [
   117.37,
   115.79
  ],
  [
   119.16,
   114.77
  ],
  [
   120.9,
   114.15
  ],
  [
   122.56,
   113.93
  ],
  [
   124.15,
   114.12
  ],
  [
   125.68,
   114.71
  ],
  [
   127.23,
   115.01
  ],
  [
   128.79,
   115.03
  ],
  [
   130.37,
   114.76
  ],
  [
   131.96,
   114.21
  ],
  [
   133.26,
   113.52
  ],
  [
   134.28,
   112.7
  ],
  [
   135,
   111.75
  ],
  [
   135.43,
   110.67
  ],
  [
   135.73,
   109.51
  ],
  [
   135.9,
   108.28
  ],
  [
   135.95,
   106.97
  ],
  [
   135.86,
   105.6
  ],
  [
   136.02,
   104.32
  ],
  [
   136.45,
   103.15
  ],
  [
   137.13,
   102.07
  ],
  [
   138.07,
   101.1
  ],
  [
   138.87,
   100.28
  ],
  [
   139.54,
   99.61
  ],
  [
   140.06,
   99.08
  ],
  [
   140.45,
   98.71
  ],
  [
   140.98,
   98.36
  ],
  [
   141.66,
   98.04
  ],
  [
   142.48,
   97.74
  ],
  [
   143.45,
   97.48
  ],
  [
   144.52,
   97.41
  ],
  [
   145.69,
   97.53
  ],
  [
   146.97,
   97.86
  ],
  [
   148.35,
   98.38
  ],
  [
   149.72,
   98.85
  ],
  [
   151.06,
   99.28
  ],
  [
   152.39,
   99.66
  ],
  [
   153.7,
   100
  ],
  [
   155.05,
   100.23
  ],
  [
   156.47,
   100.37
  ],
  [
   157.93,
   100.39
  ],
  [
   159.45,
   100.32
  ],
  [
   160.83,
   100.45
  ],
  [
   162.08,
   100.79
  ],
  [
   163.2,
   101.34
  ],
  [
   164.18,
   102.09
  ],
  [
   165.13,
   102.31
  ],
  [
   166.04,
   101.99
  ],
  [
   166.91,
   101.14
  ],
  [
   167.74,
   99.76
  ],
  [
   168.46,
   99.26
  ],
  [
   169.05,
   99.65
  ],
  [
   169.53,
   100.92
  ],
  [
   169.89,
   103.08
  ],
  [
   170.31,
   105.13
  ],
  [
   170.81,
   107.05
  ],
  [
   171.37,
   108.86
  ],
  [
   172,
   110.55
  ],
  [
   172.69,
   111.59
  ],
  [
   173.46,
   111.98
  ],
  [
   174.28,
   111.72
  ],
  [
   175.18,
   110.81
  ],
  [
   175.95,
   109.33
  ],
  [
   176.61,
   107.3
  ],
  [
   177.14,
   104.69
  ],
  [
   177.54,
   101.53
  ],
  [
   178.01,
   99.05
  ],
  [
   178.53,
   97.25
  ],
  [
   179.11,
   96.14
  ],
  [
   179.74,
   95.72
  ],
  [
   180.29,
   95.77
  ],
  [
   180.77,
   96.29
  ],
  [
   181.18,
   97.28
  ],
  [
   181.5,
   98.74
  ],
  [
   182.01,
   100.06
  ],
  [
   182.71,
   101.24
  ],
  [
   183.59,
   102.27
  ],
  [
   184.65,
   103.16
  ],
  [
   185.77,
   103.84
  ],
  [
   186.95,
   104.32
  ],
  [
   188.18,
   104.6
  ],
  [
   189.47,
   104.67
  ],
  [
   190.84,
   104.59
  ],
  [
   192.3,
   104.37
  ],
  [
   193.83,
   104
  ],
  [
   195.45,
   103.48
  ],
  [
   197.17,
   102.8
  ],
  [
   198.99,
   101.97
  ],
  [
   200.91,
   100.98
  ],
  [
   202.93,
   99.83
  ],
  [
   205.08,
   98.73
  ],
  [
   207.35,
   97.69
  ],
  [
   209.75,
   96.7
  ],
  [
   212.28,
   95.76
  ],
  [
   214.17,
   95.05
  ],
  [
   215.44,
   94.58
  ],
  [
   216.07,
   94.35
  ]
 ],
 "stations": {
  "HARROW & WEALDSTONE": {
   "zone": 5,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 0,
   "sub": 0
  },
  "KENTON": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH KENTON": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTH WEMBLEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEMBLEY CENTRAL": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 0,
   "sub": 0
  },
  "STONEBRIDGE PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "HARLESDEN": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "WILLESDEN JUNCTION": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "KENSAL GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "QUEEN'S PARK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "KILBURN PARK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "MAIDA VALE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "WARWICK AVENUE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "PADDINGTON": {
   "zone": 1,
   "lifts": 2,
   "escalators": 4,
   "lines": [
    "bakerloo",
    "circle",
    "district",
    "elizabeth",
    "hammersmith-city"
   ],
   "deep": 1,
   "sub": 1
  },
  "EDGWARE ROAD": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "bakerloo",
    "circle",
    "district",
    "hammersmith-city"
   ],
   "deep": 1,
   "sub": 1
  },
  "MARYLEBONE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "BAKER STREET": {
   "zone": 1,
   "lifts": 0,
   "escalators": 6,
   "lines": [
    "bakerloo",
    "circle",
    "hammersmith-city",
    "jubilee",
    "metropolitan"
   ],
   "deep": 1,
   "sub": 1
  },
  "REGENT'S PARK": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "OXFORD CIRCUS": {
   "zone": 1,
   "lifts": 0,
   "escalators": 14,
   "lines": [
    "bakerloo",
    "central",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "PICCADILLY CIRCUS": {
   "zone": 1,
   "lifts": 0,
   "escalators": 11,
   "lines": [
    "bakerloo",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "CHARING CROSS": {
   "zone": 1,
   "lifts": 0,
   "escalators": 10,
   "lines": [
    "bakerloo",
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "EMBANKMENT": {
   "zone": 1,
   "lifts": 0,
   "escalators": 10,
   "lines": [
    "bakerloo",
    "circle",
    "district",
    "northern"
   ],
   "deep": 1,
   "sub": 1
  },
  "WATERLOO": {
   "zone": 1,
   "lifts": 1,
   "escalators": 23,
   "lines": [
    "bakerloo",
    "jubilee",
    "northern",
    "waterloo-city"
   ],
   "deep": 1,
   "sub": 0
  },
  "LAMBETH NORTH": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "bakerloo"
   ],
   "deep": 1,
   "sub": 0
  },
  "ELEPHANT & CASTLE": {
   "zone": 1,
   "lifts": 5,
   "escalators": 0,
   "lines": [
    "bakerloo",
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "EPPING": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "THEYDON BOIS": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "DEBDEN": {
   "zone": 6,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "LOUGHTON": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "BUCKHURST HILL": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "WOODFORD": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH WOODFORD": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "SNARESBROOK": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "LEYTONSTONE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "LEYTON": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "STRATFORD": {
   "zone": 2,
   "lifts": 5,
   "escalators": 2,
   "lines": [
    "central",
    "dlr",
    "elizabeth",
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "MILE END": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central",
    "district",
    "hammersmith-city"
   ],
   "deep": 1,
   "sub": 1
  },
  "BETHNAL GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "LIVERPOOL STREET": {
   "zone": 1,
   "lifts": 1,
   "escalators": 9,
   "lines": [
    "central",
    "circle",
    "elizabeth",
    "hammersmith-city",
    "metropolitan"
   ],
   "deep": 1,
   "sub": 1
  },
  "BANK": {
   "zone": 1,
   "lifts": 5,
   "escalators": 15,
   "lines": [
    "central",
    "dlr",
    "northern",
    "waterloo-city"
   ],
   "deep": 1,
   "sub": 0
  },
  "ST PAUL'S": {
   "zone": 1,
   "lifts": 0,
   "escalators": 4,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "CHANCERY LANE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 5,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "HOLBORN": {
   "zone": 1,
   "lifts": 0,
   "escalators": 7,
   "lines": [
    "central",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "TOTTENHAM COURT ROAD": {
   "zone": 1,
   "lifts": 1,
   "escalators": 6,
   "lines": [
    "central",
    "elizabeth",
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BOND STREET": {
   "zone": 1,
   "lifts": 1,
   "escalators": 8,
   "lines": [
    "central",
    "elizabeth",
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "MARBLE ARCH": {
   "zone": 1,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "LANCASTER GATE": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "QUEENSWAY": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "NOTTING HILL GATE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 6,
   "lines": [
    "central",
    "circle",
    "district"
   ],
   "deep": 1,
   "sub": 1
  },
  "HOLLAND PARK": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "SHEPHERD'S BUSH": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "WHITE CITY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "EAST ACTON": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "NORTH ACTON": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "HANGER LANE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "PERIVALE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "GREENFORD": {
   "zone": 4,
   "lifts": 1,
   "escalators": 1,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTHOLT": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH RUISLIP": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "RUISLIP GARDENS": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST RUISLIP": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "HAINAULT": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "FAIRLOP": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "BARKINGSIDE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "NEWBURY PARK": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "GANTS HILL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "REDBRIDGE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "WANSTEAD": {
   "zone": 4,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "GRANGE HILL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "CHIGWELL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "RODING VALLEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST ACTON": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "central"
   ],
   "deep": 1,
   "sub": 0
  },
  "EALING BROADWAY": {
   "zone": 3,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "central",
    "district"
   ],
   "deep": 1,
   "sub": 0
  },
  "BAYSWATER": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "HIGH STREET KENSINGTON": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "GLOUCESTER ROAD": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "SOUTH KENSINGTON": {
   "zone": 1,
   "lifts": 0,
   "escalators": 5,
   "lines": [
    "circle",
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "SLOANE SQUARE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "VICTORIA": {
   "zone": 1,
   "lifts": 1,
   "escalators": 6,
   "lines": [
    "circle",
    "district",
    "victoria"
   ],
   "deep": 1,
   "sub": 1
  },
  "ST JAMES'S PARK": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "WESTMINSTER": {
   "zone": 1,
   "lifts": 5,
   "escalators": 17,
   "lines": [
    "circle",
    "district",
    "jubilee"
   ],
   "deep": 1,
   "sub": 1
  },
  "TEMPLE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "BLACKFRIARS": {
   "zone": 1,
   "lifts": 2,
   "escalators": 4,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "MANSION HOUSE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "CANNON STREET": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "MONUMENT": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "TOWER HILL": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "circle",
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "ALDGATE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 1
  },
  "MOORGATE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 6,
   "lines": [
    "circle",
    "hammersmith-city",
    "metropolitan",
    "northern"
   ],
   "deep": 1,
   "sub": 1
  },
  "BARBICAN": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 1
  },
  "FARRINGDON": {
   "zone": 1,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "circle",
    "elizabeth",
    "hammersmith-city",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 1
  },
  "KING'S CROSS ST PANCRAS": {
   "zone": 1,
   "lifts": 10,
   "escalators": 19,
   "lines": [
    "circle",
    "hammersmith-city",
    "metropolitan",
    "northern",
    "piccadilly",
    "victoria"
   ],
   "deep": 1,
   "sub": 1
  },
  "EUSTON SQUARE": {
   "zone": 1,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 1
  },
  "GREAT PORTLAND STREET": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 1
  },
  "ROYAL OAK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "WESTBOURNE PARK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "LADBROKE GROVE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "LATIMER ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "WOOD LANE": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "SHEPHERD'S BUSH MARKET": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "GOLDHAWK ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "circle",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "HAMMERSMITH": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "circle",
    "district",
    "hammersmith-city",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "UPMINSTER": {
   "zone": 6,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "UPMINSTER BRIDGE": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "HORNCHURCH": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "ELM PARK": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "DAGENHAM EAST": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "DAGENHAM HEATHWAY": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "BECONTREE": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "UPNEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "BARKING": {
   "zone": 4,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 0
  },
  "EAST HAM": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 0
  },
  "UPTON PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 0
  },
  "PLAISTOW": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST HAM": {
   "zone": 2,
   "lifts": 5,
   "escalators": 6,
   "lines": [
    "district",
    "dlr",
    "hammersmith-city",
    "jubilee"
   ],
   "deep": 1,
   "sub": 1
  },
  "BROMLEY-BY-BOW": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "BOW ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "STEPNEY GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "WHITECHAPEL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "elizabeth",
    "hammersmith-city",
    "windrush"
   ],
   "deep": 0,
   "sub": 1
  },
  "ALDGATE EAST": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "hammersmith-city"
   ],
   "deep": 0,
   "sub": 1
  },
  "EARL'S COURT": {
   "zone": 1,
   "lifts": 4,
   "escalators": 4,
   "lines": [
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "WEST KENSINGTON": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "BARONS COURT": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "RAVENSCOURT PARK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "STAMFORD BROOK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "TURNHAM GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 1
  },
  "CHISWICK PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "ACTON TOWN": {
   "zone": 3,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "EALING COMMON": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "GUNNERSBURY": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "KEW GARDENS": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "RICHMOND": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST BROMPTON": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "FULHAM BROADWAY": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "PARSONS GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "PUTNEY BRIDGE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "EAST PUTNEY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "SOUTHFIELDS": {
   "zone": 3,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "WIMBLEDON PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "WIMBLEDON": {
   "zone": 3,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 0
  },
  "KENSINGTON (OLYMPIA)": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "district"
   ],
   "deep": 0,
   "sub": 1
  },
  "CANNING TOWN": {
   "zone": 2,
   "lifts": 3,
   "escalators": 10,
   "lines": [
    "dlr",
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "NORTH GREENWICH": {
   "zone": 2,
   "lifts": 4,
   "escalators": 9,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "CANARY WHARF": {
   "zone": 2,
   "lifts": 3,
   "escalators": 20,
   "lines": [
    "dlr",
    "elizabeth",
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "CANADA WATER": {
   "zone": 2,
   "lifts": 4,
   "escalators": 8,
   "lines": [
    "jubilee",
    "windrush"
   ],
   "deep": 1,
   "sub": 1
  },
  "BERMONDSEY": {
   "zone": 2,
   "lifts": 1,
   "escalators": 3,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "LONDON BRIDGE": {
   "zone": 1,
   "lifts": 3,
   "escalators": 17,
   "lines": [
    "jubilee",
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "SOUTHWARK": {
   "zone": 1,
   "lifts": 2,
   "escalators": 8,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "GREEN PARK": {
   "zone": 1,
   "lifts": 5,
   "escalators": 11,
   "lines": [
    "jubilee",
    "piccadilly",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "ST JOHN'S WOOD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "SWISS COTTAGE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "FINCHLEY ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee",
    "metropolitan"
   ],
   "deep": 1,
   "sub": 1
  },
  "WEST HAMPSTEAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "KILBURN": {
   "zone": 2,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "WILLESDEN GREEN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee",
    "metropolitan"
   ],
   "deep": 1,
   "sub": 1
  },
  "DOLLIS HILL": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "NEASDEN": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 1,
   "sub": 0
  },
  "WEMBLEY PARK": {
   "zone": 4,
   "lifts": 5,
   "escalators": 0,
   "lines": [
    "jubilee",
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "KINGSBURY": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 0,
   "sub": 0
  },
  "QUEENSBURY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 0,
   "sub": 0
  },
  "CANONS PARK": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 0,
   "sub": 0
  },
  "STANMORE": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "jubilee"
   ],
   "deep": 0,
   "sub": 0
  },
  "AMERSHAM": {
   "zone": 9,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "CHALFONT & LATIMER": {
   "zone": 8,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "CHORLEYWOOD": {
   "zone": 7,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "RICKMANSWORTH": {
   "zone": 7,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "MOOR PARK": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTHWOOD": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTHWOOD HILLS": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "PINNER": {
   "zone": 5,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTH HARROW": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "HARROW-ON-THE-HILL": {
   "zone": 5,
   "lifts": 5,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORTHWICK PARK": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "PRESTON ROAD": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "CHESHAM": {
   "zone": 9,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST HARROW": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "RAYNERS LANE": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "EASTCOTE": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "RUISLIP MANOR": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "RUISLIP": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "ICKENHAM": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HILLINGDON": {
   "zone": 6,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "UXBRIDGE": {
   "zone": 6,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan",
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "CROXLEY": {
   "zone": 7,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "WATFORD": {
   "zone": 7,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "metropolitan"
   ],
   "deep": 0,
   "sub": 0
  },
  "HIGH BARNET": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "TOTTERIDGE & WHETSTONE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "WOODSIDE PARK": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST FINCHLEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "FINCHLEY CENTRAL": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "EAST FINCHLEY": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "HIGHGATE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "ARCHWAY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "TUFNELL PARK": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "KENTISH TOWN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "CAMDEN TOWN": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "MORNINGTON CRESCENT": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "EUSTON": {
   "zone": 1,
   "lifts": 0,
   "escalators": 10,
   "lines": [
    "northern",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "WARREN STREET": {
   "zone": 1,
   "lifts": 0,
   "escalators": 7,
   "lines": [
    "northern",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "GOODGE STREET": {
   "zone": 1,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "LEICESTER SQUARE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 6,
   "lines": [
    "northern",
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "KENNINGTON": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "OVAL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "STOCKWELL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "northern",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "CLAPHAM NORTH": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "CLAPHAM COMMON": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "CLAPHAM SOUTH": {
   "zone": 2,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BALHAM": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "TOOTING BEC": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "TOOTING BROADWAY": {
   "zone": 3,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "COLLIERS WOOD": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "SOUTH WIMBLEDON": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "MORDEN": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "ANGEL": {
   "zone": 1,
   "lifts": 0,
   "escalators": 6,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "OLD STREET": {
   "zone": 1,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BOROUGH": {
   "zone": 1,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "EDGWARE": {
   "zone": 5,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "BURNT OAK": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "COLINDALE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "HENDON CENTRAL": {
   "zone": 3,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BRENT CROSS": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "GOLDERS GREEN": {
   "zone": 3,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "HAMPSTEAD": {
   "zone": 2,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BELSIZE PARK": {
   "zone": 2,
   "lifts": 3,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "CHALK FARM": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "MILL HILL EAST": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 0,
   "sub": 0
  },
  "NINE ELMS": {
   "zone": 1,
   "lifts": 2,
   "escalators": 2,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "BATTERSEA POWER STATION": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "northern"
   ],
   "deep": 1,
   "sub": 0
  },
  "COCKFOSTERS": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "OAKWOOD": {
   "zone": 5,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTHGATE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "ARNOS GROVE": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "BOUNDS GREEN": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "WOOD GREEN": {
   "zone": 3,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "TURNPIKE LANE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "MANOR HOUSE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 3,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "FINSBURY PARK": {
   "zone": 2,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "piccadilly",
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "ARSENAL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "HOLLOWAY ROAD": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "CALEDONIAN ROAD": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "RUSSELL SQUARE": {
   "zone": 1,
   "lifts": 3,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "COVENT GARDEN": {
   "zone": 1,
   "lifts": 4,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "HYDE PARK CORNER": {
   "zone": 1,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "KNIGHTSBRIDGE": {
   "zone": 1,
   "lifts": 0,
   "escalators": 5,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "NORTH EALING": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "PARK ROYAL": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "ALPERTON": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "SUDBURY TOWN": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "SUDBURY HILL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH HARROW": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH EALING": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "NORTHFIELDS": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 1,
   "sub": 0
  },
  "BOSTON MANOR": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "OSTERLEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HOUNSLOW EAST": {
   "zone": 4,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HOUNSLOW CENTRAL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HOUNSLOW WEST": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HATTON CROSS": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HEATHROW TERMINALS 2 & 3": {
   "zone": 6,
   "lifts": 1,
   "escalators": 6,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HEATHROW TERMINAL 5": {
   "zone": 6,
   "lifts": 2,
   "escalators": 2,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "HEATHROW TERMINAL 4": {
   "zone": 6,
   "lifts": 1,
   "escalators": 0,
   "lines": [
    "piccadilly"
   ],
   "deep": 0,
   "sub": 0
  },
  "WALTHAMSTOW CENTRAL": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "BLACKHORSE ROAD": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "TOTTENHAM HALE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "SEVEN SISTERS": {
   "zone": 3,
   "lifts": 0,
   "escalators": 4,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "HIGHBURY & ISLINGTON": {
   "zone": 2,
   "lifts": 3,
   "escalators": 2,
   "lines": [
    "victoria",
    "windrush"
   ],
   "deep": 1,
   "sub": 0
  },
  "PIMLICO": {
   "zone": 1,
   "lifts": 0,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "VAUXHALL": {
   "zone": 1,
   "lifts": 2,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "BRIXTON": {
   "zone": 2,
   "lifts": 2,
   "escalators": 2,
   "lines": [
    "victoria"
   ],
   "deep": 1,
   "sub": 0
  },
  "ROTHERHITHE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 1
  },
  "SURREY QUAYS": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 1
  },
  "LEWISHAM": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "ELVERSON ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "DEPTFORD BRIDGE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "GREENWICH": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "CUTTY SARK (FOR MARITIME GREENWICH)": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "ISLAND GARDENS": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "MUDCHUTE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "CROSSHARBOUR": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "SOUTH QUAY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "HERON QUAYS": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST INDIA QUAY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "POPLAR": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "ALL SAINTS": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "LANGDON PARK": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "DEVONS ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "BOW CHURCH": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "PUDDING MILL LANE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "WESTFERRY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "LIMEHOUSE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "SHADWELL": {
   "zone": 2,
   "lifts": 2,
   "escalators": 0,
   "lines": [
    "dlr",
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "TOWER GATEWAY": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "BECKTON": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "GALLIONS REACH": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "CYPRUS": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "BECKTON PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "ROYAL ALBERT": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "PRINCE REGENT": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "CUSTOM HOUSE (FOR EXCEL)": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr",
    "elizabeth"
   ],
   "deep": 0,
   "sub": 0
  },
  "ROYAL VICTORIA": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "EAST INDIA": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "BLACKWALL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "WOOLWICH ARSENAL": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "KING GEORGE V": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "LONDON CITY AIRPORT": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "PONTOON DOCK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST SILVERTOWN": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "STAR LANE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "ABBEY ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "STRATFORD HIGH STREET": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "STRATFORD INTERNATIONAL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "dlr"
   ],
   "deep": 0,
   "sub": 0
  },
  "WEST CROYDON": {
   "zone": 5,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "NORWOOD JUNCTION": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "ANERLEY": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "PENGE WEST": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "SYDENHAM": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "FOREST HILL": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "HONOR OAK PARK": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "BROCKLEY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "NEW CROSS GATE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "WAPPING": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "SHOREDITCH HIGH STREET": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "HOXTON": {
   "zone": 1,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "HAGGERSTON": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "DALSTON JUNCTION": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "CANONBURY": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "CLAPHAM JUNCTION": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "WANDSWORTH ROAD": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "CLAPHAM HIGH STREET": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "DENMARK HILL": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "PECKHAM RYE": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "QUEENS ROAD PECKHAM": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "CRYSTAL PALACE": {
   "zone": 3,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "NEW CROSS": {
   "zone": 2,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "windrush"
   ],
   "deep": 0,
   "sub": 0
  },
  "WOOLWICH": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "elizabeth"
   ],
   "deep": 0,
   "sub": 1
  },
  "ABBEY WOOD": {
   "zone": 4,
   "lifts": 0,
   "escalators": 0,
   "lines": [
    "elizabeth"
   ],
   "deep": 0,
   "sub": 1
  }
 },
 "lines": {
  "bakerloo": {
   "name": "Bakerloo",
   "color": "#B36305",
   "chains": [
    [
     "HARROW & WEALDSTONE",
     "KENTON",
     "SOUTH KENTON",
     "NORTH WEMBLEY",
     "WEMBLEY CENTRAL",
     "STONEBRIDGE PARK",
     "HARLESDEN",
     "WILLESDEN JUNCTION",
     "KENSAL GREEN",
     "QUEEN'S PARK",
     "KILBURN PARK",
     "MAIDA VALE",
     "WARWICK AVENUE",
     "PADDINGTON",
     "EDGWARE ROAD",
     "MARYLEBONE",
     "BAKER STREET",
     "REGENT'S PARK",
     "OXFORD CIRCUS",
     "PICCADILLY CIRCUS",
     "CHARING CROSS",
     "EMBANKMENT",
     "WATERLOO",
     "LAMBETH NORTH",
     "ELEPHANT & CASTLE"
    ]
   ]
  },
  "central": {
   "name": "Central",
   "color": "#E32017",
   "chains": [
    [
     "EPPING",
     "THEYDON BOIS",
     "DEBDEN",
     "LOUGHTON",
     "BUCKHURST HILL",
     "WOODFORD"
    ],
    [
     "WOODFORD",
     "SOUTH WOODFORD",
     "SNARESBROOK",
     "LEYTONSTONE"
    ],
    [
     "LEYTONSTONE",
     "LEYTON",
     "STRATFORD",
     "MILE END",
     "BETHNAL GREEN",
     "LIVERPOOL STREET",
     "BANK",
     "ST PAUL'S",
     "CHANCERY LANE",
     "HOLBORN",
     "TOTTENHAM COURT ROAD",
     "OXFORD CIRCUS",
     "BOND STREET",
     "MARBLE ARCH",
     "LANCASTER GATE",
     "QUEENSWAY",
     "NOTTING HILL GATE",
     "HOLLAND PARK",
     "SHEPHERD'S BUSH",
     "WHITE CITY",
     "EAST ACTON",
     "NORTH ACTON"
    ],
    [
     "NORTH ACTON",
     "HANGER LANE",
     "PERIVALE",
     "GREENFORD",
     "NORTHOLT",
     "SOUTH RUISLIP",
     "RUISLIP GARDENS",
     "WEST RUISLIP"
    ],
    [
     "HAINAULT",
     "FAIRLOP",
     "BARKINGSIDE",
     "NEWBURY PARK",
     "GANTS HILL",
     "REDBRIDGE",
     "WANSTEAD",
     "LEYTONSTONE"
    ],
    [
     "HAINAULT",
     "GRANGE HILL",
     "CHIGWELL",
     "RODING VALLEY",
     "WOODFORD"
    ],
    [
     "NORTH ACTON",
     "WEST ACTON",
     "EALING BROADWAY"
    ]
   ]
  },
  "circle": {
   "name": "Circle",
   "color": "#FFD300",
   "pale": true,
   "chains": [
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "BAYSWATER",
     "NOTTING HILL GATE",
     "HIGH STREET KENSINGTON",
     "GLOUCESTER ROAD",
     "SOUTH KENSINGTON",
     "SLOANE SQUARE",
     "VICTORIA",
     "ST JAMES'S PARK",
     "WESTMINSTER",
     "EMBANKMENT",
     "TEMPLE",
     "BLACKFRIARS",
     "MANSION HOUSE",
     "CANNON STREET",
     "MONUMENT",
     "TOWER HILL",
     "ALDGATE",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "EDGWARE ROAD"
    ],
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "ROYAL OAK",
     "WESTBOURNE PARK",
     "LADBROKE GROVE",
     "LATIMER ROAD",
     "WOOD LANE",
     "SHEPHERD'S BUSH MARKET",
     "GOLDHAWK ROAD",
     "HAMMERSMITH"
    ]
   ]
  },
  "district": {
   "name": "District",
   "color": "#00782A",
   "chains": [
    [
     "UPMINSTER",
     "UPMINSTER BRIDGE",
     "HORNCHURCH",
     "ELM PARK",
     "DAGENHAM EAST",
     "DAGENHAM HEATHWAY",
     "BECONTREE",
     "UPNEY",
     "BARKING",
     "EAST HAM",
     "UPTON PARK",
     "PLAISTOW",
     "WEST HAM",
     "BROMLEY-BY-BOW",
     "BOW ROAD",
     "MILE END",
     "STEPNEY GREEN",
     "WHITECHAPEL",
     "ALDGATE EAST",
     "TOWER HILL",
     "MONUMENT",
     "CANNON STREET",
     "MANSION HOUSE",
     "BLACKFRIARS",
     "TEMPLE",
     "EMBANKMENT",
     "WESTMINSTER",
     "ST JAMES'S PARK",
     "VICTORIA",
     "SLOANE SQUARE",
     "SOUTH KENSINGTON",
     "GLOUCESTER ROAD",
     "EARL'S COURT"
    ],
    [
     "EARL'S COURT",
     "WEST KENSINGTON",
     "BARONS COURT",
     "HAMMERSMITH",
     "RAVENSCOURT PARK",
     "STAMFORD BROOK",
     "TURNHAM GREEN"
    ],
    [
     "TURNHAM GREEN",
     "CHISWICK PARK",
     "ACTON TOWN",
     "EALING COMMON",
     "EALING BROADWAY"
    ],
    [
     "TURNHAM GREEN",
     "GUNNERSBURY",
     "KEW GARDENS",
     "RICHMOND"
    ],
    [
     "EARL'S COURT",
     "WEST BROMPTON",
     "FULHAM BROADWAY",
     "PARSONS GREEN",
     "PUTNEY BRIDGE",
     "EAST PUTNEY",
     "SOUTHFIELDS",
     "WIMBLEDON PARK",
     "WIMBLEDON"
    ],
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "BAYSWATER",
     "NOTTING HILL GATE",
     "HIGH STREET KENSINGTON",
     "EARL'S COURT"
    ],
    [
     "EARL'S COURT",
     "KENSINGTON (OLYMPIA)"
    ]
   ]
  },
  "hammersmith-city": {
   "name": "Hammersmith & City",
   "color": "#F3A9BB",
   "pale": true,
   "chains": [
    [
     "BARKING",
     "EAST HAM",
     "UPTON PARK",
     "PLAISTOW",
     "WEST HAM",
     "BROMLEY-BY-BOW",
     "BOW ROAD",
     "MILE END",
     "STEPNEY GREEN",
     "WHITECHAPEL",
     "ALDGATE EAST",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "EDGWARE ROAD",
     "PADDINGTON",
     "ROYAL OAK",
     "WESTBOURNE PARK",
     "LADBROKE GROVE",
     "LATIMER ROAD",
     "WOOD LANE",
     "SHEPHERD'S BUSH MARKET",
     "GOLDHAWK ROAD",
     "HAMMERSMITH"
    ]
   ]
  },
  "jubilee": {
   "name": "Jubilee",
   "color": "#A0A5A9",
   "chains": [
    [
     "STRATFORD",
     "WEST HAM",
     "CANNING TOWN",
     "NORTH GREENWICH",
     "CANARY WHARF",
     "CANADA WATER",
     "BERMONDSEY",
     "LONDON BRIDGE",
     "SOUTHWARK",
     "WATERLOO",
     "WESTMINSTER",
     "GREEN PARK",
     "BOND STREET",
     "BAKER STREET",
     "ST JOHN'S WOOD",
     "SWISS COTTAGE",
     "FINCHLEY ROAD",
     "WEST HAMPSTEAD",
     "KILBURN",
     "WILLESDEN GREEN",
     "DOLLIS HILL",
     "NEASDEN",
     "WEMBLEY PARK",
     "KINGSBURY",
     "QUEENSBURY",
     "CANONS PARK",
     "STANMORE"
    ]
   ]
  },
  "metropolitan": {
   "name": "Metropolitan",
   "color": "#9B0056",
   "chains": [
    [
     "AMERSHAM",
     "CHALFONT & LATIMER"
    ],
    [
     "CHALFONT & LATIMER",
     "CHORLEYWOOD",
     "RICKMANSWORTH",
     "MOOR PARK"
    ],
    [
     "MOOR PARK",
     "NORTHWOOD",
     "NORTHWOOD HILLS",
     "PINNER",
     "NORTH HARROW",
     "HARROW-ON-THE-HILL"
    ],
    [
     "HARROW-ON-THE-HILL",
     "NORTHWICK PARK",
     "PRESTON ROAD",
     "WEMBLEY PARK"
    ],
    [
     "FINCHLEY ROAD",
     "BAKER STREET",
     "GREAT PORTLAND STREET",
     "EUSTON SQUARE",
     "KING'S CROSS ST PANCRAS",
     "FARRINGDON",
     "BARBICAN",
     "MOORGATE",
     "LIVERPOOL STREET",
     "ALDGATE"
    ],
    [
     "WEMBLEY PARK",
     "WILLESDEN GREEN",
     "FINCHLEY ROAD"
    ],
    [
     "ALDGATE",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "FINCHLEY ROAD",
     "WEMBLEY PARK",
     "PRESTON ROAD",
     "NORTHWICK PARK",
     "HARROW-ON-THE-HILL"
    ],
    [
     "CHALFONT & LATIMER",
     "CHESHAM"
    ],
    [
     "WEMBLEY PARK",
     "FINCHLEY ROAD"
    ],
    [
     "HARROW-ON-THE-HILL",
     "WEST HARROW",
     "RAYNERS LANE",
     "EASTCOTE",
     "RUISLIP MANOR",
     "RUISLIP",
     "ICKENHAM",
     "HILLINGDON",
     "UXBRIDGE"
    ],
    [
     "MOOR PARK",
     "CROXLEY",
     "WATFORD"
    ]
   ],
   "oneWay": [
    [
     "WEMBLEY PARK",
     "WILLESDEN GREEN"
    ],
    [
     "WILLESDEN GREEN",
     "FINCHLEY ROAD"
    ]
   ]
  },
  "northern": {
   "name": "Northern",
   "color": "#26221e",
   "chains": [
    [
     "HIGH BARNET",
     "TOTTERIDGE & WHETSTONE",
     "WOODSIDE PARK",
     "WEST FINCHLEY",
     "FINCHLEY CENTRAL"
    ],
    [
     "FINCHLEY CENTRAL",
     "EAST FINCHLEY",
     "HIGHGATE",
     "ARCHWAY",
     "TUFNELL PARK",
     "KENTISH TOWN",
     "CAMDEN TOWN"
    ],
    [
     "CAMDEN TOWN",
     "MORNINGTON CRESCENT",
     "EUSTON"
    ],
    [
     "EUSTON",
     "WARREN STREET",
     "GOODGE STREET",
     "TOTTENHAM COURT ROAD",
     "LEICESTER SQUARE",
     "CHARING CROSS",
     "EMBANKMENT",
     "WATERLOO",
     "KENNINGTON"
    ],
    [
     "KENNINGTON",
     "OVAL",
     "STOCKWELL",
     "CLAPHAM NORTH",
     "CLAPHAM COMMON",
     "CLAPHAM SOUTH",
     "BALHAM",
     "TOOTING BEC",
     "TOOTING BROADWAY",
     "COLLIERS WOOD",
     "SOUTH WIMBLEDON",
     "MORDEN"
    ],
    [
     "CAMDEN TOWN",
     "EUSTON"
    ],
    [
     "EUSTON",
     "KING'S CROSS ST PANCRAS",
     "ANGEL",
     "OLD STREET",
     "MOORGATE",
     "BANK",
     "LONDON BRIDGE",
     "BOROUGH",
     "ELEPHANT & CASTLE",
     "KENNINGTON"
    ],
    [
     "EDGWARE",
     "BURNT OAK",
     "COLINDALE",
     "HENDON CENTRAL",
     "BRENT CROSS",
     "GOLDERS GREEN",
     "HAMPSTEAD",
     "BELSIZE PARK",
     "CHALK FARM",
     "CAMDEN TOWN"
    ],
    [
     "MILL HILL EAST",
     "FINCHLEY CENTRAL"
    ],
    [
     "KENNINGTON",
     "NINE ELMS",
     "BATTERSEA POWER STATION"
    ]
   ]
  },
  "piccadilly": {
   "name": "Piccadilly",
   "color": "#003688",
   "chains": [
    [
     "COCKFOSTERS",
     "OAKWOOD",
     "SOUTHGATE",
     "ARNOS GROVE",
     "BOUNDS GREEN",
     "WOOD GREEN",
     "TURNPIKE LANE",
     "MANOR HOUSE",
     "FINSBURY PARK",
     "ARSENAL",
     "HOLLOWAY ROAD",
     "CALEDONIAN ROAD",
     "KING'S CROSS ST PANCRAS",
     "RUSSELL SQUARE",
     "HOLBORN",
     "COVENT GARDEN",
     "LEICESTER SQUARE",
     "PICCADILLY CIRCUS",
     "GREEN PARK",
     "HYDE PARK CORNER",
     "KNIGHTSBRIDGE",
     "SOUTH KENSINGTON",
     "GLOUCESTER ROAD",
     "EARL'S COURT",
     "BARONS COURT",
     "HAMMERSMITH",
     "TURNHAM GREEN",
     "ACTON TOWN"
    ],
    [
     "ACTON TOWN",
     "EALING COMMON",
     "NORTH EALING",
     "PARK ROYAL",
     "ALPERTON",
     "SUDBURY TOWN",
     "SUDBURY HILL",
     "SOUTH HARROW",
     "RAYNERS LANE",
     "EASTCOTE",
     "RUISLIP MANOR",
     "RUISLIP",
     "ICKENHAM",
     "HILLINGDON",
     "UXBRIDGE"
    ],
    [
     "ACTON TOWN",
     "SOUTH EALING",
     "NORTHFIELDS",
     "BOSTON MANOR",
     "OSTERLEY",
     "HOUNSLOW EAST",
     "HOUNSLOW CENTRAL",
     "HOUNSLOW WEST",
     "HATTON CROSS"
    ],
    [
     "HATTON CROSS",
     "HEATHROW TERMINALS 2 & 3",
     "HEATHROW TERMINAL 5"
    ],
    [
     "HEATHROW TERMINAL 4",
     "HEATHROW TERMINALS 2 & 3"
    ],
    [
     "HEATHROW TERMINALS 2 & 3",
     "HATTON CROSS",
     "HOUNSLOW WEST",
     "HOUNSLOW CENTRAL",
     "HOUNSLOW EAST",
     "OSTERLEY",
     "BOSTON MANOR",
     "NORTHFIELDS",
     "SOUTH EALING",
     "ACTON TOWN"
    ],
    [
     "HEATHROW TERMINAL 5",
     "HEATHROW TERMINALS 2 & 3"
    ],
    [
     "HATTON CROSS",
     "HEATHROW TERMINAL 4"
    ]
   ],
   "oneWay": [
    [
     "HEATHROW TERMINAL 4",
     "HEATHROW TERMINALS 2 & 3"
    ],
    [
     "HATTON CROSS",
     "HEATHROW TERMINAL 4"
    ]
   ]
  },
  "victoria": {
   "name": "Victoria",
   "color": "#0098D4",
   "chains": [
    [
     "WALTHAMSTOW CENTRAL",
     "BLACKHORSE ROAD",
     "TOTTENHAM HALE",
     "SEVEN SISTERS",
     "FINSBURY PARK",
     "HIGHBURY & ISLINGTON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON",
     "WARREN STREET",
     "OXFORD CIRCUS",
     "GREEN PARK",
     "VICTORIA",
     "PIMLICO",
     "VAUXHALL",
     "STOCKWELL",
     "BRIXTON"
    ]
   ]
  },
  "waterloo-city": {
   "name": "Waterloo & City",
   "color": "#95CDBA",
   "pale": true,
   "chains": [
    [
     "BANK",
     "WATERLOO"
    ]
   ]
  },
  "windrush": {
   "name": "Windrush",
   "color": "#c77b2f",
   "hollow": true,
   "chains": [
    [
     "WEST CROYDON",
     "NORWOOD JUNCTION",
     "ANERLEY",
     "PENGE WEST",
     "SYDENHAM"
    ],
    [
     "SYDENHAM",
     "FOREST HILL",
     "HONOR OAK PARK",
     "BROCKLEY",
     "NEW CROSS GATE",
     "SURREY QUAYS"
    ],
    [
     "SURREY QUAYS",
     "CANADA WATER",
     "ROTHERHITHE",
     "WAPPING",
     "SHADWELL",
     "WHITECHAPEL",
     "SHOREDITCH HIGH STREET",
     "HOXTON",
     "HAGGERSTON",
     "DALSTON JUNCTION",
     "CANONBURY",
     "HIGHBURY & ISLINGTON"
    ],
    [
     "CLAPHAM JUNCTION",
     "WANDSWORTH ROAD",
     "CLAPHAM HIGH STREET",
     "DENMARK HILL",
     "PECKHAM RYE",
     "QUEENS ROAD PECKHAM",
     "SURREY QUAYS"
    ],
    [
     "CRYSTAL PALACE",
     "SYDENHAM"
    ],
    [
     "NEW CROSS",
     "SURREY QUAYS"
    ]
   ]
  },
  "dlr": {
   "name": "DLR",
   "color": "#00A4A7",
   "chains": [
    [
     "LEWISHAM",
     "ELVERSON ROAD",
     "DEPTFORD BRIDGE",
     "GREENWICH",
     "CUTTY SARK (FOR MARITIME GREENWICH)",
     "ISLAND GARDENS",
     "MUDCHUTE",
     "CROSSHARBOUR",
     "SOUTH QUAY",
     "HERON QUAYS",
     "CANARY WHARF",
     "WEST INDIA QUAY"
    ],
    [
     "WEST INDIA QUAY",
     "POPLAR"
    ],
    [
     "POPLAR",
     "ALL SAINTS",
     "LANGDON PARK",
     "DEVONS ROAD",
     "BOW CHURCH",
     "PUDDING MILL LANE",
     "STRATFORD"
    ],
    [
     "WEST INDIA QUAY",
     "WESTFERRY"
    ],
    [
     "WESTFERRY",
     "LIMEHOUSE",
     "SHADWELL"
    ],
    [
     "SHADWELL",
     "BANK"
    ],
    [
     "SHADWELL",
     "TOWER GATEWAY"
    ],
    [
     "BECKTON",
     "GALLIONS REACH",
     "CYPRUS",
     "BECKTON PARK",
     "ROYAL ALBERT",
     "PRINCE REGENT",
     "CUSTOM HOUSE (FOR EXCEL)",
     "ROYAL VICTORIA",
     "CANNING TOWN"
    ],
    [
     "CANNING TOWN",
     "EAST INDIA",
     "BLACKWALL",
     "POPLAR"
    ],
    [
     "POPLAR",
     "WESTFERRY"
    ],
    [
     "WESTFERRY",
     "CANARY WHARF"
    ],
    [
     "CANARY WHARF",
     "HERON QUAYS",
     "SOUTH QUAY",
     "CROSSHARBOUR",
     "MUDCHUTE",
     "ISLAND GARDENS",
     "CUTTY SARK (FOR MARITIME GREENWICH)",
     "GREENWICH",
     "DEPTFORD BRIDGE",
     "ELVERSON ROAD",
     "LEWISHAM"
    ],
    [
     "WOOLWICH ARSENAL",
     "KING GEORGE V",
     "LONDON CITY AIRPORT",
     "PONTOON DOCK",
     "WEST SILVERTOWN",
     "CANNING TOWN"
    ],
    [
     "CANNING TOWN",
     "STAR LANE",
     "WEST HAM",
     "ABBEY ROAD",
     "STRATFORD HIGH STREET",
     "STRATFORD"
    ],
    [
     "STRATFORD",
     "STRATFORD INTERNATIONAL"
    ],
    [
     "POPLAR",
     "WEST INDIA QUAY",
     "CANARY WHARF"
    ]
   ],
   "oneWay": [
    [
     "WEST INDIA QUAY",
     "WESTFERRY"
    ],
    [
     "WESTFERRY",
     "CANARY WHARF"
    ]
   ]
  },
  "elizabeth": {
   "name": "Elizabeth",
   "color": "#6950A1",
   "chains": [
    [
     "PADDINGTON",
     "BOND STREET",
     "TOTTENHAM COURT ROAD",
     "FARRINGDON",
     "LIVERPOOL STREET",
     "WHITECHAPEL"
    ],
    [
     "WHITECHAPEL",
     "STRATFORD"
    ],
    [
     "WHITECHAPEL",
     "CANARY WHARF",
     "CUSTOM HOUSE (FOR EXCEL)",
     "WOOLWICH",
     "ABBEY WOOD"
    ]
   ]
  }
 },
 "stepFree": [
  "ABBEY ROAD",
  "ALL SAINTS",
  "AMERSHAM",
  "BALHAM",
  "BANK",
  "BARKING",
  "BATTERSEA POWER STATION",
  "BECKTON",
  "BECKTON PARK",
  "BERMONDSEY",
  "BLACKFRIARS",
  "BLACKHORSE ROAD",
  "BLACKWALL",
  "BOND STREET",
  "BOROUGH",
  "BOW CHURCH",
  "BRIXTON",
  "BUCKHURST HILL",
  "CALEDONIAN ROAD",
  "CANADA WATER",
  "CANARY WHARF",
  "CANNING TOWN",
  "CHESHAM",
  "COCKFOSTERS",
  "CROSSHARBOUR",
  "CUSTOM HOUSE (FOR EXCEL)",
  "CUTTY SARK (FOR MARITIME GREENWICH)",
  "CYPRUS",
  "DEPTFORD BRIDGE",
  "DEVONS ROAD",
  "EALING BROADWAY",
  "EARL'S COURT",
  "EAST INDIA",
  "EDGWARE",
  "ELVERSON ROAD",
  "EPPING",
  "FARRINGDON",
  "FINSBURY PARK",
  "FULHAM BROADWAY",
  "GALLIONS REACH",
  "GREEN PARK",
  "GREENFORD",
  "GREENWICH",
  "HAINAULT",
  "HAMMERSMITH",
  "HARROW & WEALDSTONE",
  "HARROW-ON-THE-HILL",
  "HEATHROW TERMINAL 4",
  "HEATHROW TERMINAL 5",
  "HEATHROW TERMINALS 2 & 3",
  "HENDON CENTRAL",
  "HERON QUAYS",
  "HIGHBURY & ISLINGTON",
  "HILLINGDON",
  "HOUNSLOW EAST",
  "HOUNSLOW WEST",
  "ISLAND GARDENS",
  "KENNINGTON",
  "KEW GARDENS",
  "KILBURN",
  "KING GEORGE V",
  "KING'S CROSS ST PANCRAS",
  "LANGDON PARK",
  "LEWISHAM",
  "LIMEHOUSE",
  "LIVERPOOL STREET",
  "LONDON BRIDGE",
  "LONDON CITY AIRPORT",
  "MARYLEBONE",
  "MILL HILL EAST",
  "MOOR PARK",
  "MOORGATE",
  "MORDEN",
  "MUDCHUTE",
  "NEWBURY PARK",
  "NINE ELMS",
  "NORTH GREENWICH",
  "OAKWOOD",
  "OSTERLEY",
  "PADDINGTON",
  "PONTOON DOCK",
  "POPLAR",
  "PRINCE REGENT",
  "PUDDING MILL LANE",
  "RICHMOND",
  "ROYAL ALBERT",
  "ROYAL VICTORIA",
  "SEVEN SISTERS",
  "SHADWELL",
  "SOUTH QUAY",
  "SOUTH WOODFORD",
  "SOUTHGATE",
  "SOUTHWARK",
  "STANMORE",
  "STAR LANE",
  "STOCKWELL",
  "STRATFORD",
  "STRATFORD HIGH STREET",
  "STRATFORD INTERNATIONAL",
  "SUDBURY TOWN",
  "SURREY QUAYS",
  "TOTTENHAM COURT ROAD",
  "TOTTENHAM HALE",
  "TOWER GATEWAY",
  "TOWER HILL",
  "UXBRIDGE",
  "VAUXHALL",
  "VICTORIA",
  "WATERLOO",
  "WEMBLEY CENTRAL",
  "WEMBLEY PARK",
  "WEST HAM",
  "WEST HAMPSTEAD",
  "WEST INDIA QUAY",
  "WEST SILVERTOWN",
  "WESTFERRY",
  "WESTMINSTER",
  "WHITECHAPEL",
  "WILLESDEN GREEN",
  "WIMBLEDON",
  "WOOD LANE",
  "WOODFORD",
  "WOODSIDE PARK",
  "WOOLWICH ARSENAL"
 ],
 "liftsOutSnapshot": [
  "KILBURN",
  "WEMBLEY PARK"
 ]
};
