// tube-network.js — the whole London Underground for TUBE FLOCK.
// GENERATED by tools/fetch-tube.mjs from the TfL Unified API — do not edit
// by hand; re-run the tool to refresh. Step-free list is curated (real-ish).
// Snapshot date: 2026-07-20

export const NETWORK = {
 "generated": "2026-07-20",
 "pos": {
  "HARROW & WEALDSTONE": [
   83.24,
   54.71
  ],
  "KENTON": [
   88.77,
   59.81
  ],
  "SOUTH KENTON": [
   91.32,
   65.39
  ],
  "NORTH WEMBLEY": [
   92.66,
   69.11
  ],
  "WEMBLEY CENTRAL": [
   94.81,
   74.07
  ],
  "STONEBRIDGE PARK": [
   101.14,
   78.12
  ],
  "HARLESDEN": [
   106.57,
   81.82
  ],
  "WILLESDEN JUNCTION": [
   110.67,
   83.79
  ],
  "KENSAL GREEN": [
   116.48,
   84.62
  ],
  "QUEEN'S PARK": [
   122.64,
   82.87
  ],
  "KILBURN PARK": [
   125.76,
   82.47
  ],
  "MAIDA VALE": [
   128.32,
   84.99
  ],
  "WARWICK AVENUE": [
   128.91,
   88.14
  ],
  "PADDINGTON": [
   131.04,
   91.07
  ],
  "EDGWARE ROAD": [
   133.61,
   89.76
  ],
  "MARYLEBONE": [
   135.12,
   88.6
  ],
  "BAKER STREET": [
   136.95,
   88.33
  ],
  "REGENT'S PARK": [
   140.17,
   88.1
  ],
  "OXFORD CIRCUS": [
   141.54,
   92.04
  ],
  "PICCADILLY CIRCUS": [
   143.99,
   94.54
  ],
  "CHARING CROSS": [
   145.96,
   95.82
  ],
  "EMBANKMENT": [
   147.35,
   95.99
  ],
  "WATERLOO": [
   149.72,
   97.82
  ],
  "LAMBETH NORTH": [
   150.47,
   99.99
  ],
  "ELEPHANT & CASTLE": [
   154,
   102.06
  ],
  "EPPING": [
   218.65,
   5.58
  ],
  "THEYDON BOIS": [
   215.43,
   16.2
  ],
  "DEBDEN": [
   209.61,
   28.98
  ],
  "LOUGHTON": [
   201.07,
   30.89
  ],
  "BUCKHURST HILL": [
   198.44,
   38.08
  ],
  "WOODFORD": [
   194.58,
   47.63
  ],
  "SOUTH WOODFORD": [
   192.58,
   54.89
  ],
  "SNARESBROOK": [
   190.81,
   60.33
  ],
  "LEYTONSTONE": [
   186.81,
   66.31
  ],
  "LEYTON": [
   182.67,
   72
  ],
  "STRATFORD": [
   183.3,
   79.16
  ],
  "MILE END": [
   174.19,
   87.24
  ],
  "BETHNAL GREEN": [
   167.6,
   86.23
  ],
  "LIVERPOOL STREET": [
   159.25,
   91
  ],
  "BANK": [
   157.53,
   92.94
  ],
  "ST PAUL'S": [
   154.92,
   92.18
  ],
  "CHANCERY LANE": [
   150.69,
   90.57
  ],
  "HOLBORN": [
   148.01,
   90.9
  ],
  "TOTTENHAM COURT ROAD": [
   145.01,
   91.46
  ],
  "BOND STREET": [
   139.19,
   92.48
  ],
  "MARBLE ARCH": [
   136.4,
   92.91
  ],
  "LANCASTER GATE": [
   131.41,
   93.73
  ],
  "QUEENSWAY": [
   127.9,
   94.42
  ],
  "NOTTING HILL GATE": [
   125.2,
   94.99
  ],
  "HOLLAND PARK": [
   122.31,
   95.95
  ],
  "SHEPHERD'S BUSH": [
   118.35,
   97.29
  ],
  "WHITE CITY": [
   116.7,
   93.62
  ],
  "EAST ACTON": [
   109.77,
   91.37
  ],
  "NORTH ACTON": [
   106,
   88.02
  ],
  "HANGER LANE": [
   96.07,
   84.79
  ],
  "PERIVALE": [
   86.79,
   81.63
  ],
  "GREENFORD": [
   79.98,
   78.86
  ],
  "NORTHOLT": [
   73.15,
   76.05
  ],
  "SOUTH RUISLIP": [
   64.03,
   71.87
  ],
  "RUISLIP GARDENS": [
   60.48,
   69.99
  ],
  "WEST RUISLIP": [
   52.28,
   65.65
  ],
  "HAINAULT": [
   212.53,
   49.2
  ],
  "FAIRLOP": [
   211.78,
   53.09
  ],
  "BARKINGSIDE": [
   211.05,
   57.9
  ],
  "NEWBURY PARK": [
   211.48,
   62.73
  ],
  "GANTS HILL": [
   204.3,
   62.33
  ],
  "REDBRIDGE": [
   198.02,
   62.48
  ],
  "WANSTEAD": [
   192.94,
   62.84
  ],
  "GRANGE HILL": [
   212.1,
   44.49
  ],
  "CHIGWELL": [
   206.97,
   42.29
  ],
  "RODING VALLEY": [
   197.5,
   42.64
  ],
  "WEST ACTON": [
   99.6,
   90.69
  ],
  "EALING BROADWAY": [
   93.43,
   92.14
  ],
  "BAYSWATER": [
   127.66,
   93.46
  ],
  "HIGH STREET KENSINGTON": [
   126.2,
   98.9
  ],
  "GLOUCESTER ROAD": [
   129.25,
   102.17
  ],
  "SOUTH KENSINGTON": [
   131.82,
   102.27
  ],
  "SLOANE SQUARE": [
   137.18,
   103.16
  ],
  "VICTORIA": [
   141.18,
   101.18
  ],
  "ST JAMES'S PARK": [
   144.05,
   99.63
  ],
  "WESTMINSTER": [
   146.68,
   98.77
  ],
  "TEMPLE": [
   149.88,
   94.08
  ],
  "BLACKFRIARS": [
   153.08,
   93.8
  ],
  "MANSION HOUSE": [
   155.99,
   93.54
  ],
  "CANNON STREET": [
   157.07,
   93.84
  ],
  "MONUMENT": [
   158.41,
   94.23
  ],
  "TOWER HILL": [
   161.25,
   94.58
  ],
  "ALDGATE": [
   161.51,
   92.51
  ],
  "MOORGATE": [
   157.7,
   90.61
  ],
  "BARBICAN": [
   154.79,
   89.59
  ],
  "FARRINGDON": [
   152.7,
   89.6
  ],
  "KING'S CROSS ST PANCRAS": [
   147.19,
   84.56
  ],
  "EUSTON SQUARE": [
   143.38,
   87.01
  ],
  "GREAT PORTLAND STREET": [
   140.83,
   87.86
  ],
  "ROYAL OAK": [
   127.42,
   90.15
  ],
  "WESTBOURNE PARK": [
   123.7,
   89.19
  ],
  "LADBROKE GROVE": [
   120.89,
   90.96
  ],
  "LATIMER ROAD": [
   118.66,
   92.93
  ],
  "WOOD LANE": [
   116.63,
   94.73
  ],
  "SHEPHERD'S BUSH MARKET": [
   116.07,
   96.71
  ],
  "GOLDHAWK ROAD": [
   115.97,
   98.44
  ],
  "HAMMERSMITH": [
   116.69,
   102.88
  ],
  "UPMINSTER": [
   260,
   70.8
  ],
  "UPMINSTER BRIDGE": [
   255.45,
   71.04
  ],
  "HORNCHURCH": [
   250.42,
   73.21
  ],
  "ELM PARK": [
   244.24,
   75.3
  ],
  "DAGENHAM EAST": [
   234.41,
   78.05
  ],
  "DAGENHAM HEATHWAY": [
   228.83,
   79.24
  ],
  "BECONTREE": [
   222.64,
   79.88
  ],
  "UPNEY": [
   214.96,
   80.82
  ],
  "BARKING": [
   208.78,
   80.36
  ],
  "EAST HAM": [
   199.78,
   80.55
  ],
  "UPTON PARK": [
   194.97,
   82.29
  ],
  "PLAISTOW": [
   189.6,
   84.23
  ],
  "WEST HAM": [
   185.86,
   85.78
  ],
  "BROMLEY-BY-BOW": [
   180.86,
   87.38
  ],
  "BOW ROAD": [
   176.76,
   86.36
  ],
  "STEPNEY GREEN": [
   170.29,
   88.82
  ],
  "WHITECHAPEL": [
   166.25,
   89.96
  ],
  "ALDGATE EAST": [
   162.51,
   92.13
  ],
  "EARL'S COURT": [
   126.02,
   103.26
  ],
  "WEST KENSINGTON": [
   122.02,
   104.04
  ],
  "BARONS COURT": [
   119.97,
   104.11
  ],
  "RAVENSCOURT PARK": [
   113.2,
   102.26
  ],
  "STAMFORD BROOK": [
   110.24,
   101.88
  ],
  "TURNHAM GREEN": [
   107.57,
   101.76
  ],
  "CHISWICK PARK": [
   103.52,
   102.02
  ],
  "ACTON TOWN": [
   99.76,
   97.93
  ],
  "EALING COMMON": [
   97.4,
   94.5
  ],
  "GUNNERSBURY": [
   101.32,
   103.38
  ],
  "KEW GARDENS": [
   98.32,
   110.53
  ],
  "RICHMOND": [
   93.46,
   117.22
  ],
  "WEST BROMPTON": [
   125.35,
   105.58
  ],
  "FULHAM BROADWAY": [
   125.4,
   109.06
  ],
  "PARSONS GREEN": [
   123.67,
   111.39
  ],
  "PUTNEY BRIDGE": [
   121.39,
   114.79
  ],
  "EAST PUTNEY": [
   120.71,
   119.18
  ],
  "SOUTHFIELDS": [
   122.03,
   126.02
  ],
  "WIMBLEDON PARK": [
   124.11,
   131.11
  ],
  "WIMBLEDON": [
   122.04,
   137.59
  ],
  "KENSINGTON (OLYMPIA)": [
   121,
   100.56
  ],
  "CANNING TOWN": [
   186.85,
   92.83
  ],
  "NORTH GREENWICH": [
   185.63,
   99.19
  ],
  "CANARY WHARF": [
   178.84,
   97.72
  ],
  "CANADA WATER": [
   169.44,
   100.42
  ],
  "BERMONDSEY": [
   165.04,
   100.5
  ],
  "LONDON BRIDGE": [
   157.54,
   96.64
  ],
  "SOUTHWARK": [
   152.57,
   97.34
  ],
  "GREEN PARK": [
   141.28,
   96.05
  ],
  "ST JOHN'S WOOD": [
   131.88,
   82.69
  ],
  "SWISS COTTAGE": [
   131.59,
   78.25
  ],
  "FINCHLEY ROAD": [
   130.1,
   76.73
  ],
  "WEST HAMPSTEAD": [
   126.72,
   76.82
  ],
  "KILBURN": [
   122.74,
   76.56
  ],
  "WILLESDEN GREEN": [
   117.53,
   75.6
  ],
  "DOLLIS HILL": [
   112.24,
   74.24
  ],
  "NEASDEN": [
   108.99,
   73.26
  ],
  "WEMBLEY PARK": [
   100.12,
   68.8
  ],
  "KINGSBURY": [
   100.26,
   58.31
  ],
  "QUEENSBURY": [
   98.02,
   53.78
  ],
  "CANONS PARK": [
   95.47,
   47.24
  ],
  "STANMORE": [
   92.88,
   41.36
  ],
  "AMERSHAM": [
   1.07,
   15.06
  ],
  "CHALFONT & LATIMER": [
   15.25,
   18.03
  ],
  "CHORLEYWOOD": [
   27.98,
   24.63
  ],
  "RICKMANSWORTH": [
   41.48,
   31.49
  ],
  "MOOR PARK": [
   53.92,
   36.51
  ],
  "NORTHWOOD": [
   56.52,
   45.61
  ],
  "NORTHWOOD HILLS": [
   60.85,
   50.69
  ],
  "PINNER": [
   69.39,
   54.41
  ],
  "NORTH HARROW": [
   75.04,
   58.3
  ],
  "HARROW-ON-THE-HILL": [
   82.64,
   61.05
  ],
  "NORTHWICK PARK": [
   88.42,
   61.39
  ],
  "PRESTON ROAD": [
   95.34,
   64.55
  ],
  "CHESHAM": [
   0,
   0
  ],
  "WEST HARROW": [
   77.76,
   60.8
  ],
  "RAYNERS LANE": [
   72.42,
   63.01
  ],
  "EASTCOTE": [
   64.5,
   62.35
  ],
  "RUISLIP MANOR": [
   59.8,
   63.95
  ],
  "RUISLIP": [
   57.1,
   64.85
  ],
  "ICKENHAM": [
   51.04,
   69.38
  ],
  "HILLINGDON": [
   48.68,
   73.39
  ],
  "UXBRIDGE": [
   40.2,
   76.86
  ],
  "CROXLEY": [
   51.13,
   28.18
  ],
  "WATFORD": [
   58.47,
   23.14
  ],
  "HIGH BARNET": [
   125.74,
   26.48
  ],
  "TOTTERIDGE & WHETSTONE": [
   130.29,
   36.15
  ],
  "WOODSIDE PARK": [
   128.42,
   42.24
  ],
  "WEST FINCHLEY": [
   127.53,
   46.4
  ],
  "FINCHLEY CENTRAL": [
   126.28,
   50.52
  ],
  "EAST FINCHLEY": [
   134.58,
   57.2
  ],
  "HIGHGATE": [
   140.35,
   61.85
  ],
  "ARCHWAY": [
   143.68,
   67.69
  ],
  "TUFNELL PARK": [
   142.59,
   71.89
  ],
  "KENTISH TOWN": [
   141.9,
   75.04
  ],
  "CAMDEN TOWN": [
   141.29,
   80.38
  ],
  "MORNINGTON CRESCENT": [
   142.48,
   82.61
  ],
  "EUSTON": [
   143.99,
   85.85
  ],
  "WARREN STREET": [
   142.62,
   87.33
  ],
  "GOODGE STREET": [
   143.82,
   89.43
  ],
  "LEICESTER SQUARE": [
   145.61,
   93.9
  ],
  "KENNINGTON": [
   152.38,
   105.06
  ],
  "OVAL": [
   150.43,
   108.21
  ],
  "STOCKWELL": [
   147.35,
   112.89
  ],
  "CLAPHAM NORTH": [
   145.13,
   116.3
  ],
  "CLAPHAM COMMON": [
   142.63,
   117.95
  ],
  "CLAPHAM SOUTH": [
   139.83,
   122.35
  ],
  "BALHAM": [
   138.2,
   126.89
  ],
  "TOOTING BEC": [
   136.17,
   130.57
  ],
  "TOOTING BROADWAY": [
   133.56,
   134.47
  ],
  "COLLIERS WOOD": [
   130.63,
   139.06
  ],
  "SOUTH WIMBLEDON": [
   126.43,
   140.44
  ],
  "MORDEN": [
   125.58,
   146.82
  ],
  "ANGEL": [
   152.27,
   83.99
  ],
  "OLD STREET": [
   157.87,
   86.88
  ],
  "BOROUGH": [
   156.18,
   98.83
  ],
  "EDGWARE": [
   101.43,
   44.35
  ],
  "BURNT OAK": [
   104.71,
   49.62
  ],
  "COLINDALE": [
   108.97,
   53.19
  ],
  "HENDON CENTRAL": [
   116.05,
   59.06
  ],
  "BRENT CROSS": [
   119.92,
   62.28
  ],
  "GOLDERS GREEN": [
   125.82,
   64.41
  ],
  "HAMPSTEAD": [
   130.82,
   72.17
  ],
  "BELSIZE PARK": [
   134.68,
   75.04
  ],
  "CHALK FARM": [
   138.08,
   78.04
  ],
  "MILL HILL EAST": [
   121.01,
   46.98
  ],
  "NINE ELMS": [
   145.59,
   109.15
  ],
  "BATTERSEA POWER STATION": [
   141.47,
   109.14
  ],
  "COCKFOSTERS": [
   139.35,
   26.01
  ],
  "OAKWOOD": [
   144.48,
   27.85
  ],
  "SOUTHGATE": [
   145.79,
   35.31
  ],
  "ARNOS GROVE": [
   144.21,
   43
  ],
  "BOUNDS GREEN": [
   146.87,
   47.56
  ],
  "WOOD GREEN": [
   151.2,
   52.19
  ],
  "TURNPIKE LANE": [
   153.29,
   55.68
  ],
  "MANOR HOUSE": [
   155.35,
   65.14
  ],
  "FINSBURY PARK": [
   152.12,
   68.33
  ],
  "ARSENAL": [
   151.93,
   71
  ],
  "HOLLOWAY ROAD": [
   150.19,
   73.88
  ],
  "CALEDONIAN ROAD": [
   148.6,
   75.91
  ],
  "RUSSELL SQUARE": [
   146.86,
   88.24
  ],
  "COVENT GARDEN": [
   146.81,
   93.07
  ],
  "HYDE PARK CORNER": [
   138.37,
   97.94
  ],
  "KNIGHTSBRIDGE": [
   135.93,
   98.61
  ],
  "NORTH EALING": [
   97.22,
   90.93
  ],
  "PARK ROYAL": [
   98.59,
   86.27
  ],
  "ALPERTON": [
   93.98,
   79.73
  ],
  "SUDBURY TOWN": [
   89.12,
   74.8
  ],
  "SUDBURY HILL": [
   82.88,
   71.83
  ],
  "SOUTH HARROW": [
   78.04,
   67.98
  ],
  "SOUTH EALING": [
   91.63,
   98.93
  ],
  "NORTHFIELDS": [
   89.43,
   99.74
  ],
  "BOSTON MANOR": [
   86.34,
   101.53
  ],
  "OSTERLEY": [
   78.12,
   108.49
  ],
  "HOUNSLOW EAST": [
   76.83,
   112.39
  ],
  "HOUNSLOW CENTRAL": [
   73.79,
   113.32
  ],
  "HOUNSLOW WEST": [
   67.77,
   112.27
  ],
  "HATTON CROSS": [
   56.71,
   115.52
  ],
  "HEATHROW TERMINALS 2 & 3": [
   47.95,
   113.35
  ],
  "HEATHROW TERMINAL 5": [
   36.4,
   113.92
  ],
  "HEATHROW TERMINAL 4": [
   49.9,
   119.51
  ],
  "WALTHAMSTOW CENTRAL": [
   178.34,
   59.22
  ],
  "BLACKHORSE ROAD": [
   171.93,
   57.31
  ],
  "TOTTENHAM HALE": [
   166.17,
   56.73
  ],
  "SEVEN SISTERS": [
   162.45,
   59.04
  ],
  "HIGHBURY & ISLINGTON": [
   153.18,
   76.96
  ],
  "PIMLICO": [
   144,
   104.7
  ],
  "VAUXHALL": [
   146.88,
   106.32
  ],
  "BRIXTON": [
   149.69,
   117.52
  ],
  "ROTHERHITHE": [
   168.67,
   99.01
  ],
  "SURREY QUAYS": [
   170,
   102.62
  ]
 },
 "lines": {
  "bakerloo": {
   "name": "Bakerloo",
   "color": "#B36305",
   "chains": [
    [
     "HARROW & WEALDSTONE",
     "KENTON",
     "SOUTH KENTON",
     "NORTH WEMBLEY",
     "WEMBLEY CENTRAL",
     "STONEBRIDGE PARK",
     "HARLESDEN",
     "WILLESDEN JUNCTION",
     "KENSAL GREEN",
     "QUEEN'S PARK",
     "KILBURN PARK",
     "MAIDA VALE",
     "WARWICK AVENUE",
     "PADDINGTON",
     "EDGWARE ROAD",
     "MARYLEBONE",
     "BAKER STREET",
     "REGENT'S PARK",
     "OXFORD CIRCUS",
     "PICCADILLY CIRCUS",
     "CHARING CROSS",
     "EMBANKMENT",
     "WATERLOO",
     "LAMBETH NORTH",
     "ELEPHANT & CASTLE"
    ]
   ]
  },
  "central": {
   "name": "Central",
   "color": "#E32017",
   "chains": [
    [
     "EPPING",
     "THEYDON BOIS",
     "DEBDEN",
     "LOUGHTON",
     "BUCKHURST HILL",
     "WOODFORD"
    ],
    [
     "WOODFORD",
     "SOUTH WOODFORD",
     "SNARESBROOK",
     "LEYTONSTONE"
    ],
    [
     "LEYTONSTONE",
     "LEYTON",
     "STRATFORD",
     "MILE END",
     "BETHNAL GREEN",
     "LIVERPOOL STREET",
     "BANK",
     "ST PAUL'S",
     "CHANCERY LANE",
     "HOLBORN",
     "TOTTENHAM COURT ROAD",
     "OXFORD CIRCUS",
     "BOND STREET",
     "MARBLE ARCH",
     "LANCASTER GATE",
     "QUEENSWAY",
     "NOTTING HILL GATE",
     "HOLLAND PARK",
     "SHEPHERD'S BUSH",
     "WHITE CITY",
     "EAST ACTON",
     "NORTH ACTON"
    ],
    [
     "NORTH ACTON",
     "HANGER LANE",
     "PERIVALE",
     "GREENFORD",
     "NORTHOLT",
     "SOUTH RUISLIP",
     "RUISLIP GARDENS",
     "WEST RUISLIP"
    ],
    [
     "HAINAULT",
     "FAIRLOP",
     "BARKINGSIDE",
     "NEWBURY PARK",
     "GANTS HILL",
     "REDBRIDGE",
     "WANSTEAD",
     "LEYTONSTONE"
    ],
    [
     "HAINAULT",
     "GRANGE HILL",
     "CHIGWELL",
     "RODING VALLEY",
     "WOODFORD"
    ],
    [
     "NORTH ACTON",
     "WEST ACTON",
     "EALING BROADWAY"
    ]
   ]
  },
  "circle": {
   "name": "Circle",
   "color": "#FFD300",
   "pale": true,
   "chains": [
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "BAYSWATER",
     "NOTTING HILL GATE",
     "HIGH STREET KENSINGTON",
     "GLOUCESTER ROAD",
     "SOUTH KENSINGTON",
     "SLOANE SQUARE",
     "VICTORIA",
     "ST JAMES'S PARK",
     "WESTMINSTER",
     "EMBANKMENT",
     "TEMPLE",
     "BLACKFRIARS",
     "MANSION HOUSE",
     "CANNON STREET",
     "MONUMENT",
     "TOWER HILL",
     "ALDGATE",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "EDGWARE ROAD"
    ],
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "ROYAL OAK",
     "WESTBOURNE PARK",
     "LADBROKE GROVE",
     "LATIMER ROAD",
     "WOOD LANE",
     "SHEPHERD'S BUSH MARKET",
     "GOLDHAWK ROAD",
     "HAMMERSMITH"
    ]
   ]
  },
  "district": {
   "name": "District",
   "color": "#00782A",
   "chains": [
    [
     "UPMINSTER",
     "UPMINSTER BRIDGE",
     "HORNCHURCH",
     "ELM PARK",
     "DAGENHAM EAST",
     "DAGENHAM HEATHWAY",
     "BECONTREE",
     "UPNEY",
     "BARKING",
     "EAST HAM",
     "UPTON PARK",
     "PLAISTOW",
     "WEST HAM",
     "BROMLEY-BY-BOW",
     "BOW ROAD",
     "MILE END",
     "STEPNEY GREEN",
     "WHITECHAPEL",
     "ALDGATE EAST",
     "TOWER HILL",
     "MONUMENT",
     "CANNON STREET",
     "MANSION HOUSE",
     "BLACKFRIARS",
     "TEMPLE",
     "EMBANKMENT",
     "WESTMINSTER",
     "ST JAMES'S PARK",
     "VICTORIA",
     "SLOANE SQUARE",
     "SOUTH KENSINGTON",
     "GLOUCESTER ROAD",
     "EARL'S COURT"
    ],
    [
     "EARL'S COURT",
     "WEST KENSINGTON",
     "BARONS COURT",
     "HAMMERSMITH",
     "RAVENSCOURT PARK",
     "STAMFORD BROOK",
     "TURNHAM GREEN"
    ],
    [
     "TURNHAM GREEN",
     "CHISWICK PARK",
     "ACTON TOWN",
     "EALING COMMON",
     "EALING BROADWAY"
    ],
    [
     "TURNHAM GREEN",
     "GUNNERSBURY",
     "KEW GARDENS",
     "RICHMOND"
    ],
    [
     "EARL'S COURT",
     "WEST BROMPTON",
     "FULHAM BROADWAY",
     "PARSONS GREEN",
     "PUTNEY BRIDGE",
     "EAST PUTNEY",
     "SOUTHFIELDS",
     "WIMBLEDON PARK",
     "WIMBLEDON"
    ],
    [
     "EDGWARE ROAD",
     "PADDINGTON",
     "BAYSWATER",
     "NOTTING HILL GATE",
     "HIGH STREET KENSINGTON",
     "EARL'S COURT"
    ],
    [
     "EARL'S COURT",
     "KENSINGTON (OLYMPIA)"
    ]
   ]
  },
  "hammersmith-city": {
   "name": "Hammersmith & City",
   "color": "#F3A9BB",
   "pale": true,
   "chains": [
    [
     "BARKING",
     "EAST HAM",
     "UPTON PARK",
     "PLAISTOW",
     "WEST HAM",
     "BROMLEY-BY-BOW",
     "BOW ROAD",
     "MILE END",
     "STEPNEY GREEN",
     "WHITECHAPEL",
     "ALDGATE EAST",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "EDGWARE ROAD",
     "PADDINGTON",
     "ROYAL OAK",
     "WESTBOURNE PARK",
     "LADBROKE GROVE",
     "LATIMER ROAD",
     "WOOD LANE",
     "SHEPHERD'S BUSH MARKET",
     "GOLDHAWK ROAD",
     "HAMMERSMITH"
    ]
   ]
  },
  "jubilee": {
   "name": "Jubilee",
   "color": "#A0A5A9",
   "chains": [
    [
     "STRATFORD",
     "WEST HAM",
     "CANNING TOWN",
     "NORTH GREENWICH",
     "CANARY WHARF",
     "CANADA WATER",
     "BERMONDSEY",
     "LONDON BRIDGE",
     "SOUTHWARK",
     "WATERLOO",
     "WESTMINSTER",
     "GREEN PARK",
     "BOND STREET",
     "BAKER STREET",
     "ST JOHN'S WOOD",
     "SWISS COTTAGE",
     "FINCHLEY ROAD",
     "WEST HAMPSTEAD",
     "KILBURN",
     "WILLESDEN GREEN",
     "DOLLIS HILL",
     "NEASDEN",
     "WEMBLEY PARK",
     "KINGSBURY",
     "QUEENSBURY",
     "CANONS PARK",
     "STANMORE"
    ]
   ]
  },
  "metropolitan": {
   "name": "Metropolitan",
   "color": "#9B0056",
   "chains": [
    [
     "AMERSHAM",
     "CHALFONT & LATIMER"
    ],
    [
     "CHALFONT & LATIMER",
     "CHORLEYWOOD",
     "RICKMANSWORTH",
     "MOOR PARK"
    ],
    [
     "MOOR PARK",
     "NORTHWOOD",
     "NORTHWOOD HILLS",
     "PINNER",
     "NORTH HARROW",
     "HARROW-ON-THE-HILL"
    ],
    [
     "HARROW-ON-THE-HILL",
     "NORTHWICK PARK",
     "PRESTON ROAD",
     "WEMBLEY PARK"
    ],
    [
     "FINCHLEY ROAD",
     "BAKER STREET",
     "GREAT PORTLAND STREET",
     "EUSTON SQUARE",
     "KING'S CROSS ST PANCRAS",
     "FARRINGDON",
     "BARBICAN",
     "MOORGATE",
     "LIVERPOOL STREET",
     "ALDGATE"
    ],
    [
     "WEMBLEY PARK",
     "WILLESDEN GREEN",
     "FINCHLEY ROAD"
    ],
    [
     "ALDGATE",
     "LIVERPOOL STREET",
     "MOORGATE",
     "BARBICAN",
     "FARRINGDON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON SQUARE",
     "GREAT PORTLAND STREET",
     "BAKER STREET",
     "FINCHLEY ROAD",
     "WEMBLEY PARK",
     "PRESTON ROAD",
     "NORTHWICK PARK",
     "HARROW-ON-THE-HILL"
    ],
    [
     "CHALFONT & LATIMER",
     "CHESHAM"
    ],
    [
     "WEMBLEY PARK",
     "FINCHLEY ROAD"
    ],
    [
     "HARROW-ON-THE-HILL",
     "WEST HARROW",
     "RAYNERS LANE",
     "EASTCOTE",
     "RUISLIP MANOR",
     "RUISLIP",
     "ICKENHAM",
     "HILLINGDON",
     "UXBRIDGE"
    ],
    [
     "MOOR PARK",
     "CROXLEY",
     "WATFORD"
    ]
   ]
  },
  "northern": {
   "name": "Northern",
   "color": "#26221e",
   "chains": [
    [
     "HIGH BARNET",
     "TOTTERIDGE & WHETSTONE",
     "WOODSIDE PARK",
     "WEST FINCHLEY",
     "FINCHLEY CENTRAL"
    ],
    [
     "FINCHLEY CENTRAL",
     "EAST FINCHLEY",
     "HIGHGATE",
     "ARCHWAY",
     "TUFNELL PARK",
     "KENTISH TOWN",
     "CAMDEN TOWN"
    ],
    [
     "CAMDEN TOWN",
     "MORNINGTON CRESCENT",
     "EUSTON"
    ],
    [
     "EUSTON",
     "WARREN STREET",
     "GOODGE STREET",
     "TOTTENHAM COURT ROAD",
     "LEICESTER SQUARE",
     "CHARING CROSS",
     "EMBANKMENT",
     "WATERLOO",
     "KENNINGTON"
    ],
    [
     "KENNINGTON",
     "OVAL",
     "STOCKWELL",
     "CLAPHAM NORTH",
     "CLAPHAM COMMON",
     "CLAPHAM SOUTH",
     "BALHAM",
     "TOOTING BEC",
     "TOOTING BROADWAY",
     "COLLIERS WOOD",
     "SOUTH WIMBLEDON",
     "MORDEN"
    ],
    [
     "CAMDEN TOWN",
     "EUSTON"
    ],
    [
     "EUSTON",
     "KING'S CROSS ST PANCRAS",
     "ANGEL",
     "OLD STREET",
     "MOORGATE",
     "BANK",
     "LONDON BRIDGE",
     "BOROUGH",
     "ELEPHANT & CASTLE",
     "KENNINGTON"
    ],
    [
     "EDGWARE",
     "BURNT OAK",
     "COLINDALE",
     "HENDON CENTRAL",
     "BRENT CROSS",
     "GOLDERS GREEN",
     "HAMPSTEAD",
     "BELSIZE PARK",
     "CHALK FARM",
     "CAMDEN TOWN"
    ],
    [
     "MILL HILL EAST",
     "FINCHLEY CENTRAL"
    ],
    [
     "KENNINGTON",
     "NINE ELMS",
     "BATTERSEA POWER STATION"
    ]
   ]
  },
  "piccadilly": {
   "name": "Piccadilly",
   "color": "#003688",
   "chains": [
    [
     "COCKFOSTERS",
     "OAKWOOD",
     "SOUTHGATE",
     "ARNOS GROVE",
     "BOUNDS GREEN",
     "WOOD GREEN",
     "TURNPIKE LANE",
     "MANOR HOUSE",
     "FINSBURY PARK",
     "ARSENAL",
     "HOLLOWAY ROAD",
     "CALEDONIAN ROAD",
     "KING'S CROSS ST PANCRAS",
     "RUSSELL SQUARE",
     "HOLBORN",
     "COVENT GARDEN",
     "LEICESTER SQUARE",
     "PICCADILLY CIRCUS",
     "GREEN PARK",
     "HYDE PARK CORNER",
     "KNIGHTSBRIDGE",
     "SOUTH KENSINGTON",
     "GLOUCESTER ROAD",
     "EARL'S COURT",
     "BARONS COURT",
     "HAMMERSMITH",
     "TURNHAM GREEN",
     "ACTON TOWN"
    ],
    [
     "ACTON TOWN",
     "EALING COMMON",
     "NORTH EALING",
     "PARK ROYAL",
     "ALPERTON",
     "SUDBURY TOWN",
     "SUDBURY HILL",
     "SOUTH HARROW",
     "RAYNERS LANE",
     "EASTCOTE",
     "RUISLIP MANOR",
     "RUISLIP",
     "ICKENHAM",
     "HILLINGDON",
     "UXBRIDGE"
    ],
    [
     "ACTON TOWN",
     "SOUTH EALING",
     "NORTHFIELDS",
     "BOSTON MANOR",
     "OSTERLEY",
     "HOUNSLOW EAST",
     "HOUNSLOW CENTRAL",
     "HOUNSLOW WEST",
     "HATTON CROSS"
    ],
    [
     "HATTON CROSS",
     "HEATHROW TERMINALS 2 & 3",
     "HEATHROW TERMINAL 5"
    ],
    [
     "HEATHROW TERMINAL 4",
     "HEATHROW TERMINALS 2 & 3"
    ],
    [
     "HEATHROW TERMINALS 2 & 3",
     "HATTON CROSS",
     "HOUNSLOW WEST",
     "HOUNSLOW CENTRAL",
     "HOUNSLOW EAST",
     "OSTERLEY",
     "BOSTON MANOR",
     "NORTHFIELDS",
     "SOUTH EALING",
     "ACTON TOWN"
    ],
    [
     "HEATHROW TERMINAL 5",
     "HEATHROW TERMINALS 2 & 3"
    ],
    [
     "HATTON CROSS",
     "HEATHROW TERMINAL 4"
    ]
   ]
  },
  "victoria": {
   "name": "Victoria",
   "color": "#0098D4",
   "chains": [
    [
     "WALTHAMSTOW CENTRAL",
     "BLACKHORSE ROAD",
     "TOTTENHAM HALE",
     "SEVEN SISTERS",
     "FINSBURY PARK",
     "HIGHBURY & ISLINGTON",
     "KING'S CROSS ST PANCRAS",
     "EUSTON",
     "WARREN STREET",
     "OXFORD CIRCUS",
     "GREEN PARK",
     "VICTORIA",
     "PIMLICO",
     "VAUXHALL",
     "STOCKWELL",
     "BRIXTON"
    ]
   ]
  },
  "waterloo-city": {
   "name": "Waterloo & City",
   "color": "#95CDBA",
   "pale": true,
   "chains": [
    [
     "BANK",
     "WATERLOO"
    ]
   ]
  },
  "windrush": {
   "name": "Windrush",
   "color": "#c77b2f",
   "hollow": true,
   "chains": [
    [
     "ROTHERHITHE",
     "CANADA WATER",
     "SURREY QUAYS"
    ]
   ]
  }
 },
 "stepFree": [
  "AMERSHAM",
  "BALHAM",
  "BARKING",
  "BATTERSEA POWER STATION",
  "BERMONDSEY",
  "BLACKFRIARS",
  "BLACKHORSE ROAD",
  "BOND STREET",
  "BOROUGH",
  "BRIXTON",
  "BUCKHURST HILL",
  "CALEDONIAN ROAD",
  "CANADA WATER",
  "CANARY WHARF",
  "CANNING TOWN",
  "CHESHAM",
  "COCKFOSTERS",
  "EALING BROADWAY",
  "EARL'S COURT",
  "EDGWARE",
  "EPPING",
  "FARRINGDON",
  "FINSBURY PARK",
  "FULHAM BROADWAY",
  "GREEN PARK",
  "GREENFORD",
  "HAINAULT",
  "HAMMERSMITH",
  "HARROW & WEALDSTONE",
  "HARROW-ON-THE-HILL",
  "HEATHROW TERMINAL 4",
  "HEATHROW TERMINAL 5",
  "HEATHROW TERMINALS 2 & 3",
  "HENDON CENTRAL",
  "HIGHBURY & ISLINGTON",
  "HILLINGDON",
  "HOUNSLOW EAST",
  "HOUNSLOW WEST",
  "KENNINGTON",
  "KEW GARDENS",
  "KILBURN",
  "KING'S CROSS ST PANCRAS",
  "LIVERPOOL STREET",
  "LONDON BRIDGE",
  "MARYLEBONE",
  "MILL HILL EAST",
  "MOOR PARK",
  "MOORGATE",
  "MORDEN",
  "NEWBURY PARK",
  "NINE ELMS",
  "NORTH GREENWICH",
  "OAKWOOD",
  "OSTERLEY",
  "PADDINGTON",
  "RICHMOND",
  "SEVEN SISTERS",
  "SOUTH WOODFORD",
  "SOUTHGATE",
  "SOUTHWARK",
  "STANMORE",
  "STOCKWELL",
  "STRATFORD",
  "SUDBURY TOWN",
  "SURREY QUAYS",
  "TOTTENHAM COURT ROAD",
  "TOTTENHAM HALE",
  "TOWER HILL",
  "UXBRIDGE",
  "VAUXHALL",
  "VICTORIA",
  "WATERLOO",
  "WEMBLEY CENTRAL",
  "WEMBLEY PARK",
  "WEST HAM",
  "WEST HAMPSTEAD",
  "WESTMINSTER",
  "WHITECHAPEL",
  "WILLESDEN GREEN",
  "WIMBLEDON",
  "WOOD LANE",
  "WOODFORD",
  "WOODSIDE PARK"
 ],
 "liftsOutSnapshot": [
  "ICKENHAM",
  "KILBURN",
  "WEMBLEY PARK"
 ]
};
