# Delivery directions for eleven_v3: each voiced line's spoken text with audio tags ([drily], [sighs] ...). The tags
# are for the voice only; voices.json keeps the plain text (what the page shows) in "text" and the directed text in
# "say". Run: python3 tools/directions.py <lines.json from tools/lines.mjs>  -> writes voices.json
import json, re, sys
DEFAULT = {
    'narrator': '[dry, unhurried]', 'quaile': '[drily]', 'sam': '[measured]', 'gerald': '[booming, pompous]',
    'margaret': '[cool, precise]', 'clement': '[nervous, too quick]', 'dilys': '[loud, cheerful]', 'toby': '[breezy, smug]',
}
SAY = {
    'p1-open': '[warm, wry] The Steeple Wyke Horticultural Show, the hundred and twelfth. [beat] You have been a detective sergeant in this county for nineteen days.',
    'p1a-1': '[amused] Bunting, a marquee, a brass band from the next village, and four hundred people who know each other\'s business.',
    'p1b-1': '[brisk, pleased] You came. Good. I\'m judging the chutney, and you\'re holding the spoons.',
    'p1b-2': '[polite, wary] Ma\'am, I was told this was a day off.',
    'p1b-3': '[cheerfully] It is. [beat] Nobody has ever been murdered over chutney.',
    'p1c-1': '[shouting into a microphone, pompous] Gerald Pike, chairman. The marrow results are delayed. [irritated] Would whoever has moved the marrows please put them back.',
    'p1c-2': '[shouting into a microphone, stern] And the vicar\'s cordial is in the church-hall flasks again. Do not take them home.',
    'p1c-3': '[deadpan] He has judged the marrows for thirty-one years. His own marrow has won for nine.',
    'p1d-2': '[slightly uneasy] The straw Gerald has a red rosette, and faces the wrong way.',
    'p1d-3': '[deadpan] Behind the produce tent, somebody screams. [beat] It is a short scream, and then a very English apology.',
    'p2-open': '[low] Gerald Pike is in a deckchair behind the produce tent, with his hat over his face. [dry] The woman who screamed is still apologising.',
    'p2a-2': '[calm, firm] Keep them back, Sam. Use your height.',
    'p2b-1': '[quiet] No pulse. His hand is cool. Under the hat his face is calm, as if somebody has just told him his marrow won.',
    'p2b-2': '[quietly, all business] Don\'t move him. Ring it in. Then look at what\'s on the grass.',
    'p2c-2': '[thinking aloud] He told everybody not to take them home.',
    'p2c-3': '[sharp] Then why has he got one?',
    'p2d-1': '[weary] Seventy-two, heavy, red in the face, a hot day. The doctor will say heart.',
    'p2d-2': '[curious] And you\'ll say?',
    'p2d-3': '[drily, certain] I\'ll say a man who tells four hundred people not to touch the vicar\'s flasks doesn\'t drink from one.',
    'p2d-4': '[brisk] The prize-giving is at seven, and the whole village will be in one room. We have till then.',
    'hub-0': '[brisk] Five people to see before seven, and time for four. [beat] Where first?',
    'hub-3': '[tired, wry] One more, then the pub. My feet have been judging chutney since nine.',
    'hub-n': '[brisk] Where next?',
    'evening': '[sighs, then brightly] That\'s the light gone. Pub, Sam. I\'m buying, so it\'s halves.',
    'p3-open': '[gentle] Margaret Pike is in her garden, two fields from the show, deadheading roses. Nobody has told her. [quiet] You have to.',
    'p3-open-b': '[slightly unsettled] Margaret Pike is back in her garden, deadheading roses, as if the afternoon were any other.',
    'p3a-b1': '[cool, faintly mocking] You\'ve been in his study, Sergeant. Did you find what you wanted?',
    'p3a-b2': '[guarded] Some of it.',
    'p3a-1': '[gently, carefully] Mrs Pike, I\'m sorry. Your husband has died.',
    'p3a-2': '[flat, after a pause] At the show?',
    'p3a-3': '[gently] Behind the produce tent.',
    'p3a-4': '[dry, not unkind] He\'d have wanted to be in front of it.',
    'p3b-1': '[precise] Gerald only drank from the green flask. Elderflower. He made it himself, [dry] and nobody else would touch it.',
    'p3b-2': '[a little weary] He forgot it this morning. He forgot it every morning, and I took it down to him at twelve.',
    'p3b-3': '[quiet] Not today?',
    'p3b-4': '[cool] Not today. [beat] I had the roses.',
    'p3e-1': '[recognising it, cool] That\'s the vicar\'s. Clement takes Gerald a cup of his cordial at every show, [dry] and Gerald tips it on the nearest roses when Clement has gone.',
    'p3e-2': '[quietly, pointed] He must have been thirsty today.',
    'p3c-2': '[cool, challenging] If you want to know whether I\'ve cut any foxgloves, Sergeant, count them.',
    'p3d-2': '[uneasy, quiet] At the end of the border stands the scarecrow in the panama hat. An hour ago it was at the show.',
    'p3d-3': '[flat] That\'s not ours.',
    'p4b-1': '[laughs] Dilys Rudd, Rudd\'s Butchers. I didn\'t kill him, love. [cheerful] I was weighing.',
    'p4b-2': '[mild, probing] I\'m told he was going to disqualify you this year.',
    'p4b-3': '[grinning] He was going to try.',
    'p4c-2': '[unashamed, loud] Water. Two pints a night, straight up the stalk. Every grower in this tent does it. [scornful] Gerald just never caught anyone else.',
    'p4c-3': '[drily] Is that a confession?',
    'p4c-4': '[laughs] To marrows, yes.',
    'p4f-1': '[lowering her voice, enjoying it] The vicar. Behind the produce tent, about one. Gerald was waving his little notebook at him.',
    'p4f-2': '[sarcastic] Then they shook hands, and the vicar went and fetched him a drink. Very Christian.',
    'p4d-2': '[surprised] He did it too.',
    'p4d-3': '[delighted, loud] Thirty-one years. Write that down, love. Big letters.',
    'p5b-1': '[distracted, smooth] Sorry, sorry. Clients. Toby Pike, Pike and Lowe, Cirencester. [beat] Is it Dad?',
    'p5b-2': '[gently] I\'m sorry.',
    'p5b-3': '[briefly thrown, then businesslike] Right. Right. Is there a form for probate, or do I just ring someone?',
    'p5c-1': '[glib] In the car, on a call to a man in Swindon from half one till twenty past two. He wants a barn.',
    'p5c-3': '[mild] Your father owned the fields behind the church.',
    'p5c-4': '[unembarrassed] Forty houses, if the parish council sees sense. Dad wouldn\'t. I\'m not hiding it.',
    'p5e-1': '[amused] The vicar? Dad said he couldn\'t add up. Said it twice this week, [laughs] which for Dad is practically a sermon.',
    'p5e-2': '[already turning away] Sorry, I have to take this. It\'s Swindon.',
    'p5d-2': '[uneasy, deadpan] In the back of the brass band\'s minibus, the straw vicar sits with its seatbelt on.',
    'p6a-1': '[flustered, eager] Sergeant! Inspector! Dreadful. [rushed] I\'ve been on the cake stall all afternoon, you can ask anyone.',
    'p6a-2': '[drily] Nobody\'s asked you yet, Vicar.',
    'p6a-3': '[embarrassed laugh] No. Quite. Sorry. [too bright] Cordial?',
    'p6e-1': '[forced laugh] Gerald wrote everything down. He once wrote down my sermon. [nervous] And timed it.',
    'p6e-2': '[quietly] Did he time this?',
    'p6b-2': '[too quickly] Slugs.',
    'p6b-3': '[deadpan] Slugs with secateurs?',
    'p6b-4': '[weakly] Very determined slugs.',
    'p6c-2': '[babbling] One always goes walkabout at the show. Gerald\'s very strict about it. [catches himself] Was.',
    'p6d-3': '[drily] Generous parish.',
    'p6d-4': '[too quickly] An anonymous donor.',
    'p7a-2': '[cool, uneasy] That wasn\'t there this morning either.',
    'p7b-1': '[dry] He kept the Society\'s books in there. He was treasurer before Clement, and he never forgave him for being better at it.',
    'p7b-3': '[dry] Clement was nicer at it.',
    'p7c-4': '[cool, deliberate] The vicar came at four, to pray with me. He asked to sit in here on his own for a while.',
    'p7c-5': '[drily] And did he pray?',
    'p7c-6': '[dry] He looked in the drawers. I suppose that\'s a kind of prayer.',
    'p7c-2': '[realising] After the marrows. He was going to ask him today.',
    'p7c-3': '[quietly] And he never got past the marrows.',
    'p7d-2': '[deadpan] I\'d have poisoned him over that alone.',
    'p7d-3': '[shocked] Ma\'am.',
    'p7d-4': '[cheerfully] I\'m deaf in one ear, Sam. I can say what I like.',
    'p8b-1': '[mouth half full, amused] Go on, then. Who did it?',
    'p8b-2': '[matter-of-fact] Foxglove\'s digitalis. On a hot day it stops a big man\'s heart, and it looks like a big man\'s heart on a hot day.',
    'p8e-good': '[smiling] I think you know, and I think you\'d like me to say it. [beat] I shan\'t.',
    'p8e-vic': '[pointed] Nobody\'s been to look at the vicar\'s garden. I\'d have looked at the vicar\'s garden.',
    'p8e-study': '[pointed] A chairman keeps notes. Nobody\'s read Gerald\'s.',
    'p8e-ask': '[thoughtful] Gerald didn\'t drink that flask by himself. Somebody saw who handed it to him. [knowing] Somebody always sees.',
    'p8d-2': '[weary] Don\'t. It happens every year. Nobody owns up.',
    'p9a-1': '[over-bright, into a microphone] The Pike Cup for the heaviest marrow goes this year to Mrs Dilys Rudd.',
    'p9d-1': '[quietly] Your hall, Sergeant.',
    'p9e-notebook': '[steady, clear] The prize fund was four thousand short, and Gerald wrote it down: ask C, after the marrows.',
    'p9e-argument': '[steady] At one o\'clock he showed you that notebook behind the produce tent. Then you fetched him a drink.',
    'p9e-poured': '[steady, pressing] He never drank your cordial. He poured it on the roses. So today you stayed and watched him drink it.',
    'p9e-foxglove': '[firm] Six foxgloves cut in your garden. Not slugs.',
    'p9e-study': '[firm] And at four you were in his study, looking for the notebook.',
    'p9e-flask': '[quiet, final] He died with one of your flasks by his chair.',
    'p9e-hunch': '[relieved, too loud] I was on the cake stall all afternoon. Ask anyone.',
    'p9e-sit': '[quietly, tired] Sit down, Sam. Not tonight.',
    'p9f-margaret': '[icy] I had forty-one foxgloves this morning, Sergeant. I still have forty-one. Count them.',
    'p9f-dilys': '[outraged, loud] I put water in marrows, love. Not in men.',
    'p9f-toby': '[offended, smug] I was in a field with a man from Swindon. There\'s a video. [beat] It\'s very long.',
    'p9g-1': '[firm, unhurried] Sit down, Sam. [beat] Vicar, the prize fund is four thousand short, and your roof is not. Gerald was going to say so, after the marrows.',
    'p9g-2': '[quietly] Sit down, Sam.',
    'p9h-1': '[breaking, fast] He was going to stand up here and say it. In front of everyone. [voice cracking] In front of the roof.',
    'p9h-2': '[small, ashamed] I only wanted him to be ill. For the afternoon.',
    'p9h-3': '[quiet, not unkind] The roof will still leak, Vicar.',
    'p10b-2': '[cool, faint smile] Thank you, Sergeant. You were very thorough. They look nice indoors, [dry] as long as nobody drinks the water.',
    'p10b-3': '[cool, pointed] The vicar called this morning, to see how I was. I didn\'t offer him anything.',
    'p10c-2': '[warm, grudging] You did well, Sam. For nineteen days.',
    'p10c-5': '[drily] Next time, look at the vicar first. In my experience it\'s the vicar a surprising amount of the time.',
    'p10c-6': '[grim, dry] We\'ll have him on the prize fund by Friday. The foxgloves will take longer.',
    'p10c-7': '[sighs] Well. Nobody\'s dead who wasn\'t dead yesterday.',
    'p10c-3': '[amused] Twenty.',
    'p10c-4': '[loudly, cupping an ear] Hm? Other side, Sam. That one\'s off.',
    'p10d-3': '[amused, then uneasy] Twenty days, and they\'ve made you already. That\'s quick.',
    'p10d-4': '[very quiet] Nobody entered it.',
    'p10d-6': '[very quiet] Nobody entered it. [beat] The card on the straw vicar beside it says Best in Show.',
}
TAG = re.compile(r'\[[^\]]*\]\s*')
def plain(s): return re.sub(r'\s+', ' ', TAG.sub('', s)).strip()
lines = json.load(open(sys.argv[1]))
voices = json.load(open('bible/characters.json'))
vmap = {c['id']: c['voice'] for c in voices['characters']}; vmap['narrator'] = voices['narrator']['voice']
bad = []
out = {}
for k in sorted(lines):
    v = lines[k]
    say = SAY.get(k) or f"{DEFAULT[v['speaker']]} {v['text']}"
    if plain(say) != v['text']: bad.append(k)
    out[k] = {'speaker': v['speaker'], 'text': v['text'], 'say': say}
extra = [k for k in SAY if k not in lines]
if bad or extra: sys.exit(f'directions out of step: {bad} {extra}')
json.dump({'about': 'Every voiced line of marrow.ink: who speaks it, the exact words shown on the page ("text"), and what the voice is given ("say": the same words with eleven_v3 audio tags). tools/lines.mjs --check voices.json proves "text" matches the ink; tools/directions.py writes this file. Each line has two takes, media/vo/<id>-1.mp3 and -2.mp3; the page plays one at random.',
           'model': 'eleven_v3', 'takes': 2, 'voices': vmap, 'lines': out}, open('voices.json', 'w'), indent=1, ensure_ascii=False)
print(len(out), 'lines;', len(SAY), 'with their own direction')
