// GENERATED by build-channels.mjs — do not edit by hand.
// Source: magpie/robbin/audio/ (24 tracks)
export const CHANNELS = [
  {
    "id": "the-quiet-engines",
    "name": "The Quiet Engines",
    "tag": "core",
    "url": "../../../magpie/robbin/audio/the-quiet-engines.mp3"
  },
  {
    "id": "the-inexorable-passacaglia",
    "name": "The Inexorable Passacaglia",
    "tag": "core",
    "url": "../../../magpie/robbin/audio/the-inexorable-passacaglia.mp3"
  },
  {
    "id": "per-station/barbican-telematics-for-the-ages-remastered",
    "name": "Barbican Telematics For The Ages Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/barbican-telematics-for-the-ages-remastered.mp3"
  },
  {
    "id": "per-station/camden-town-canary-2",
    "name": "Camden Town Canary 2",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/camden-town-canary-2.mp3"
  },
  {
    "id": "per-station/canary-wharf-whisper-choir-remastered-x2",
    "name": "Canary Wharf Whisper Choir Remastered X2",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/canary-wharf-whisper-choir-remastered-x2.mp3"
  },
  {
    "id": "per-station/euston-night-mail-remastered",
    "name": "Euston Night Mail Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/euston-night-mail-remastered.mp3"
  },
  {
    "id": "per-station/gloucester-road-americana-d-remastered",
    "name": "Gloucester Road Americana D Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/gloucester-road-americana-d-remastered.mp3"
  },
  {
    "id": "per-station/leicester-square-subjunction-fn",
    "name": "Leicester Square Subjunction Fn",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/leicester-square-subjunction-fn.mp3"
  },
  {
    "id": "per-station/london-bridge-gogogo-remastered",
    "name": "London Bridge Gogogo Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/london-bridge-gogogo-remastered.mp3"
  },
  {
    "id": "per-station/london-city-airport-paper-plane",
    "name": "London City Airport Paper Plane",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/london-city-airport-paper-plane.mp3"
  },
  {
    "id": "per-station/moorgate-backlot-2",
    "name": "Moorgate Backlot 2",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/moorgate-backlot-2.mp3"
  },
  {
    "id": "per-station/piccadilly-circus-wiggly-wiggle-remastered",
    "name": "Piccadilly Circus Wiggly Wiggle Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/piccadilly-circus-wiggly-wiggle-remastered.mp3"
  },
  {
    "id": "per-station/south-kensington-muntelo-remastered",
    "name": "South Kensington Muntelo Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/south-kensington-muntelo-remastered.mp3"
  },
  {
    "id": "per-station/st-pauls-gregorians",
    "name": "St Pauls Gregorians",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/st-pauls-gregorians.mp3"
  },
  {
    "id": "per-station/stratford-candied-waters-remastered",
    "name": "Stratford Candied Waters Remastered",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/stratford-candied-waters-remastered.mp3"
  },
  {
    "id": "per-station/temple-claudes-lament-redux-guest-vocal",
    "name": "Temple Claudes Lament Redux Guest Vocal",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/temple-claudes-lament-redux-guest-vocal.mp3"
  },
  {
    "id": "per-station/westminster-spring",
    "name": "Westminster Spring",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/westminster-spring.mp3"
  },
  {
    "id": "per-station/whitechapel-candy-code-waiting",
    "name": "Whitechapel Candy Code Waiting",
    "tag": "station",
    "url": "../../../magpie/robbin/audio/per-station/whitechapel-candy-code-waiting.mp3"
  },
  {
    "id": "generic/aching-evocative-space-waltz",
    "name": "Aching Evocative Space Waltz",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/aching-evocative-space-waltz.mp3"
  },
  {
    "id": "generic/gears-and-birdcalls",
    "name": "Gears And Birdcalls",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/gears-and-birdcalls.mp3"
  },
  {
    "id": "generic/hypnotic-sleepy-loops",
    "name": "Hypnotic Sleepy Loops",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/hypnotic-sleepy-loops.mp3"
  },
  {
    "id": "generic/the-alchemists-ball",
    "name": "The Alchemists Ball",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/the-alchemists-ball.mp3"
  },
  {
    "id": "generic/the-stone-ostinato",
    "name": "The Stone Ostinato",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/the-stone-ostinato.mp3"
  },
  {
    "id": "generic/the-weight-of-motion",
    "name": "The Weight Of Motion",
    "tag": "rotation",
    "url": "../../../magpie/robbin/audio/generic/the-weight-of-motion.mp3"
  }
];
