name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Update HTML with version info directly
        run: |
          # Get repo info
          REPO_URL="https://github.com/danbri/glitchcan-minigam"
          LAST_COMMIT_DATE=$(git log -1 --format="%ci")
          LAST_COMMIT_ID=$(git rev-parse --short HEAD)
          LAST_COMMIT_URL="$REPO_URL/commit/$LAST_COMMIT_ID"
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Get thumbwar.html info
          THUMBWAR_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- thumbwar/thumbwar.html)
          THUMBWAR_LAST_COMMIT_ID=$(git log -1 --format="%h" -- thumbwar/thumbwar.html)
          THUMBWAR_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- thumbwar/thumbwar.html)"
          
          # Create a temporary HTML file for replacement
          THUMBWAR_META_HTML="<!-- BEGIN: AUTO-GENERATED THUMBWAR METADATA -->
              <p>
                Last modified: $THUMBWAR_LAST_COMMIT_DATE<br>
                Version: <span class=\"version-badge\">$THUMBWAR_LAST_COMMIT_ID</span><br>
                <a href=\"$THUMBWAR_COMMIT_URL\" target=\"_blank\">View changes</a> | 
                <a href=\"$REPO_URL/blob/master/thumbwar/thumbwar.html\" target=\"_blank\">View source</a> | 
                <a href=\"$REPO_URL/commits/master/thumbwar/thumbwar.html\" target=\"_blank\">History</a>
              </p>
              <!-- END: AUTO-GENERATED THUMBWAR METADATA -->"
          
          # Update HTML directly using sed
          # Replace the loading placeholders with actual content
          sed -i "s|<span id=\"last-commit-date\">Loading...</span>|<span id=\"last-commit-date\"><!-- AUTO-GENERATED -->$LAST_COMMIT_DATE<!-- /AUTO-GENERATED --></span>|g" index.html
          sed -i "s|<span id=\"latest-commit-id\">Loading...</span>|<span id=\"latest-commit-id\"><!-- AUTO-GENERATED -->$LAST_COMMIT_ID<!-- /AUTO-GENERATED --></span>|g" index.html
          sed -i "s|<a id=\"latest-commit-link\" href=\"#\" target=\"_blank\">|<a id=\"latest-commit-link\" href=\"$LAST_COMMIT_URL\" target=\"_blank\">|g" index.html
          sed -i "s|<span id=\"latest-commit-message\">Loading...</span>|<span id=\"latest-commit-message\"><!-- AUTO-GENERATED -->$LAST_COMMIT_MSG<!-- /AUTO-GENERATED --></span>|g" index.html
          
          # Replace the entire thumbwar-meta div content
          sed -i "s|<div class=\"game-meta\" id=\"thumbwar-meta\">.*<\/div>|<div class=\"game-meta\" id=\"thumbwar-meta\">$THUMBWAR_META_HTML</div>|s" index.html

      - name: Remove version-info.js script tag
        run: |
          # Remove script tag since we're no longer using JavaScript for version info
          sed -i '/<script src="version-info.js"><\/script>/d' index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1