name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Print diagnostics
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Content of index.html:"
          cat index.html
      
      - name: Update HTML with version info directly
        run: |
          # Get repo info
          REPO_URL="https://github.com/danbri/glitchcan-minigam"
          LAST_COMMIT_DATE=$(git log -1 --format="%ci")
          LAST_COMMIT_ID=$(git rev-parse --short HEAD)
          LAST_COMMIT_URL="$REPO_URL/commit/$LAST_COMMIT_ID"
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Get thumbwar.html info
          THUMBWAR_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- thumbwar/thumbwar.html)
          THUMBWAR_LAST_COMMIT_ID=$(git log -1 --format="%h" -- thumbwar/thumbwar.html)
          THUMBWAR_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- thumbwar/thumbwar.html)"
          
          # Get inklet.html info
          INKLET_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- inklet/inklet.html)
          INKLET_LAST_COMMIT_ID=$(git log -1 --format="%h" -- inklet/inklet.html)
          INKLET_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- inklet/inklet.html)"
          
          # Create a temporary HTML file for replacement - Thumbwar
          THUMBWAR_META_HTML="<!-- BEGIN: AUTO-GENERATED THUMBWAR METADATA -->
              <p>
                Last modified: $THUMBWAR_LAST_COMMIT_DATE<br>
                Version: <span class=\"version-badge\">$THUMBWAR_LAST_COMMIT_ID</span><br>
                <a href=\"$THUMBWAR_COMMIT_URL\" target=\"_blank\">View changes</a> | 
                <a href=\"$REPO_URL/blob/master/thumbwar/thumbwar.html\" target=\"_blank\">View source</a> | 
                <a href=\"$REPO_URL/commits/master/thumbwar/thumbwar.html\" target=\"_blank\">History</a>
              </p>
              <!-- END: AUTO-GENERATED THUMBWAR METADATA -->"
          
          # Create a temporary HTML file for replacement - Inklet
          INKLET_META_HTML="<!-- BEGIN: AUTO-GENERATED INKLET METADATA -->
              <p>
                Last modified: $INKLET_LAST_COMMIT_DATE<br>
                Version: <span class=\"version-badge\">$INKLET_LAST_COMMIT_ID</span><br>
                <a href=\"$INKLET_COMMIT_URL\" target=\"_blank\">View changes</a> | 
                <a href=\"$REPO_URL/blob/master/inklet/inklet.html\" target=\"_blank\">View source</a> | 
                <a href=\"$REPO_URL/commits/master/inklet/inklet.html\" target=\"_blank\">History</a>
              </p>
              <!-- END: AUTO-GENERATED INKLET METADATA -->"
          
          # Update HTML directly using sed
          # Replace the loading placeholders with actual content
          sed -i "s|<span id=\"last-commit-date\">Loading...</span>|<span id=\"last-commit-date\"><!-- AUTO-GENERATED -->$LAST_COMMIT_DATE<!-- /AUTO-GENERATED --></span>|g" index.html
          sed -i "s|<span id=\"latest-commit-id\">Loading...</span>|<span id=\"latest-commit-id\"><!-- AUTO-GENERATED -->$LAST_COMMIT_ID<!-- /AUTO-GENERATED --></span>|g" index.html
          sed -i "s|<a id=\"latest-commit-link\" href=\"#\" target=\"_blank\">|<a id=\"latest-commit-link\" href=\"$LAST_COMMIT_URL\" target=\"_blank\">|g" index.html
          sed -i "s|<span id=\"latest-commit-message\">Loading...</span>|<span id=\"latest-commit-message\"><!-- AUTO-GENERATED -->$LAST_COMMIT_MSG<!-- /AUTO-GENERATED --></span>|g" index.html
          
          # Debug - view the current content
          echo "Checking current index.html content:"
          grep -A3 "game-meta" index.html
          
          # Save metadata to files first to avoid issues with special characters and multiline content
          echo "$THUMBWAR_META_HTML" > thumbwar_meta.html
          echo "$INKLET_META_HTML" > inklet_meta.html
          
          # Replace the game-meta div content using awk for more reliable multiline replacement
          awk '{
            if (match($0, /<div class="game-meta" id="thumbwar-meta">/)) {
              system("cat thumbwar_meta.html");
              inDiv = 1;
            } else if (match($0, /<div class="game-meta" id="inklet-meta">/)) {
              system("cat inklet_meta.html");
              inDiv = 1;
            } else if (inDiv && match($0, /<\/div>/)) {
              print "</div>";
              inDiv = 0;
            } else if (!inDiv) {
              print $0;
            }
          }' index.html > index.html.new
          
          mv index.html.new index.html
          
          # Debug - verify the replacement worked
          echo "Checking updated index.html content:"
          grep -A5 "game-meta" index.html

      - name: Remove version-info.js script tag
        run: |
          # Remove script tag since we're no longer using JavaScript for version info
          sed -i '/<script src="version-info.js"><\/script>/d' index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Print final HTML
        run: |
          echo "Final content of index.html:"
          cat index.html
          echo "Directory structure:"
          find . -type f -name "*.html" | sort
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4