name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Print diagnostics
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Content of index.html:"
          cat index.html
      
      - name: Update HTML with version info directly
        run: |
          # Get repo info
          REPO_URL="https://github.com/danbri/glitchcan-minigam"
          LAST_COMMIT_DATE=$(git log -1 --format="%ci")
          LAST_COMMIT_ID=$(git rev-parse --short HEAD)
          LAST_COMMIT_URL="$REPO_URL/commit/$LAST_COMMIT_ID"
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Get game HTML file info
          THUMBWAR_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- thumbwar/thumbwar.html)
          THUMBWAR_LAST_COMMIT_ID=$(git log -1 --format="%h" -- thumbwar/thumbwar.html)
          THUMBWAR_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- thumbwar/thumbwar.html)"
          
          INKLET_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- inklet/inklet.html)
          INKLET_LAST_COMMIT_ID=$(git log -1 --format="%h" -- inklet/inklet.html)
          INKLET_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- inklet/inklet.html)"
          
          TOKITOKIPONA_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- tokitokipona/tokitokipona.html)
          TOKITOKIPONA_LAST_COMMIT_ID=$(git log -1 --format="%h" -- tokitokipona/tokitokipona.html)
          TOKITOKIPONA_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- tokitokipona/tokitokipona.html)"
          
          SCHEMOIDS_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- schemoids/schemoids.html)
          SCHEMOIDS_LAST_COMMIT_ID=$(git log -1 --format="%h" -- schemoids/schemoids.html)
          SCHEMOIDS_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- schemoids/schemoids.html)"
          
          LIGHTSHOW_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- lightshow/bookshelf-a.html)
          LIGHTSHOW_LAST_COMMIT_ID=$(git log -1 --format="%h" -- lightshow/bookshelf-a.html)
          LIGHTSHOW_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- lightshow/bookshelf-a.html)"
          
          SANDPIT_LAST_COMMIT_DATE=$(git log -1 --format="%ci" -- sandpit/sandpit.html)
          SANDPIT_LAST_COMMIT_ID=$(git log -1 --format="%h" -- sandpit/sandpit.html)
          SANDPIT_COMMIT_URL="$REPO_URL/commit/$(git log -1 --format="%H" -- sandpit/sandpit.html)"
          
          # Update index.html with commit info using direct string replacement
          # First, update repository information
          sed -i "s|<span id=\"last-commit-date\">Loading...</span>|<span id=\"last-commit-date\">$LAST_COMMIT_DATE</span>|g" index.html
          sed -i "s|<span id=\"latest-commit-id\">Loading...</span>|<span id=\"latest-commit-id\">$LAST_COMMIT_ID</span>|g" index.html
          sed -i "s|<a id=\"latest-commit-link\" href=\"#\" target=\"_blank\">|<a id=\"latest-commit-link\" href=\"$LAST_COMMIT_URL\" target=\"_blank\">|g" index.html
          sed -i "s|<span id=\"latest-commit-message\">Loading...</span>|<span id=\"latest-commit-message\">$LAST_COMMIT_MSG</span>|g" index.html
          
          # Now replace game metadata
          # Thumbwar metadata
          THUMBWAR_META="<p>Last modified: $THUMBWAR_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$THUMBWAR_LAST_COMMIT_ID</span><br><a href=\"$THUMBWAR_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/thumbwar/thumbwar.html\" target=\"_blank\">View source</a> | <a href=\"$REPO_URL/commits/master/thumbwar/thumbwar.html\" target=\"_blank\">History</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"thumbwar-meta\">.*<\/div>|<div class=\"game-meta\" id=\"thumbwar-meta\">$THUMBWAR_META</div>|" index.html
          
          # Inklet metadata
          INKLET_META="<p>Last modified: $INKLET_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$INKLET_LAST_COMMIT_ID</span><br><a href=\"$INKLET_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/inklet/inklet.html\" target=\"_blank\">View source</a> | <a href=\"$REPO_URL/commits/master/inklet/inklet.html\" target=\"_blank\">History</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"inklet-meta\">.*<\/div>|<div class=\"game-meta\" id=\"inklet-meta\">$INKLET_META</div>|" index.html
          
          # Tokitokipona metadata
          TOKITOKIPONA_META="<p>Last modified: $TOKITOKIPONA_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$TOKITOKIPONA_LAST_COMMIT_ID</span><br><a href=\"$TOKITOKIPONA_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/tokitokipona/tokitokipona.html\" target=\"_blank\">View source</a> | <a href=\"$REPO_URL/commits/master/tokitokipona/tokitokipona.html\" target=\"_blank\">History</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"tokitokipona-meta\">.*<\/div>|<div class=\"game-meta\" id=\"tokitokipona-meta\">$TOKITOKIPONA_META</div>|" index.html
          
          # Schemoids metadata
          SCHEMOIDS_META="<p>Last modified: $SCHEMOIDS_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$SCHEMOIDS_LAST_COMMIT_ID</span><br><a href=\"$SCHEMOIDS_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/schemoids/schemoids.html\" target=\"_blank\">View source</a> | <a href=\"$REPO_URL/commits/master/schemoids/schemoids.html\" target=\"_blank\">History</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"schemoids-meta\">.*<\/div>|<div class=\"game-meta\" id=\"schemoids-meta\">$SCHEMOIDS_META</div>|" index.html
          
          # Lightshow metadata
          LIGHTSHOW_META="<p>Last modified: $LIGHTSHOW_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$LIGHTSHOW_LAST_COMMIT_ID</span><br><a href=\"$LIGHTSHOW_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/lightshow/bookshelf-a.html\" target=\"_blank\">View source A</a> | <a href=\"$REPO_URL/blob/master/lightshow/bookshelf-b.html\" target=\"_blank\">View source B</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"lightshow-meta\">.*<\/div>|<div class=\"game-meta\" id=\"lightshow-meta\">$LIGHTSHOW_META</div>|" index.html
          
          # Sandpit metadata
          SANDPIT_META="<p>Last modified: $SANDPIT_LAST_COMMIT_DATE<br>Version: <span class=\"version-badge\">$SANDPIT_LAST_COMMIT_ID</span><br><a href=\"$SANDPIT_COMMIT_URL\" target=\"_blank\">View changes</a> | <a href=\"$REPO_URL/blob/master/sandpit/sandpit.html\" target=\"_blank\">View source</a> | <a href=\"$REPO_URL/commits/master/sandpit/sandpit.html\" target=\"_blank\">History</a></p>"
          sed -i "s|<div class=\"game-meta\" id=\"sandpit-meta\">.*<\/div>|<div class=\"game-meta\" id=\"sandpit-meta\">$SANDPIT_META</div>|" index.html
          
          # Debug - verify the replacement worked
          echo "Checking updated index.html content:"
          grep -A1 "game-meta" index.html
          grep -A5 "game-meta" index.html

      - name: Remove version-info.js script tag
        run: |
          # Remove script tag since we're no longer using JavaScript for version info
          sed -i '/<script src="version-info.js"><\/script>/d' index.html
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Print final HTML
        run: |
          echo "Final content of index.html:"
          cat index.html
          echo "Directory structure:"
          find . -type f -name "*.html" | sort
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4